INSERT INTO public.sentences (id,list_id,ru,ru_stressed,translit,en,pl,de,sort_order) VALUES
('hangingout-part-1-1','hangingout-part-1','Я встречаюсь с друзьями.','Я встреча́юсь с друзья́ми.','Ya vstrechayus s druzyami.','I meet my friends.','Spotykam się z przyjaciółmi.','Ich treffe meine Freunde.',1),
('hangingout-part-1-2','hangingout-part-1','Мы часто проводим время вместе.','Мы ча́сто прово́дим вре́мя вме́сте.','My chasto provodim vremya vmeste.','We often spend time together.','Często spędzamy razem czas.','Wir verbringen oft Zeit zusammen.',2),
('hangingout-part-1-3','hangingout-part-1','Мы идём в кафе.','Мы идём в кафе́.','My idyom v kafe.','We go to a café.','Idziemy do kawiarni.','Wir gehen in ein Café.',3),
('hangingout-part-1-4','hangingout-part-1','Мы пьём кофе.','Мы пьём ко́фе.','My pyom kofe.','We drink coffee.','Pijemy kawę.','Wir trinken Kaffee.',4),
('hangingout-part-1-5','hangingout-part-1','Мы разговариваем.','Мы разгова́риваем.','My razgovarivayem.','We talk.','Rozmawiamy.','Wir reden.',5),
('hangingout-part-1-6','hangingout-part-1','Мы смеёмся вместе.','Мы смеёмся вме́сте.','My smeyomsya vmeste.','We laugh together.','Śmiejemy się razem.','Wir lachen zusammen.',6),
('hangingout-part-1-7','hangingout-part-1','Я звоню своему другу.','Я звоню́ своему́ дру́гу.','Ya zvonyu svoyemu drugu.','I call my friend.','Dzwonię do mojego przyjaciela.','Ich rufe meinen Freund an.',7),
('hangingout-part-1-8','hangingout-part-1','Мы встречаемся вечером.','Мы встреча́емся ве́чером.','My vstrechayemsya vecherom.','We meet in the evening.','Spotykamy się wieczorem.','Wir treffen uns am Abend.',8),
('hangingout-part-1-9','hangingout-part-1','Мы гуляем по городу.','Мы гуля́ем по го́роду.','My gulyayem po gorodu.','We walk around the city.','Spacerujemy po mieście.','Wir gehen durch die Stadt.',9),
('hangingout-part-1-10','hangingout-part-1','Мы сидим в парке.','Мы сиди́м в па́рке.','My sidim v parke.','We sit in the park.','Siedzimy w parku.','Wir sitzen im Park.',10),
('hangingout-part-1-11','hangingout-part-1','Погода хорошая.','Пого́да хоро́шая.','Pogoda khoroshaya.','The weather is nice.','Pogoda jest ładna.','Das Wetter ist schön.',11),
('hangingout-part-1-12','hangingout-part-1','Мы наслаждаемся днём.','Мы наслажда́емся днём.','My naslazhdayemsya dnyom.','We enjoy the day.','Cieszymy się dniem.','Wir genießen den Tag.',12),
('hangingout-part-1-13','hangingout-part-1','Мы обсуждаем работу.','Мы обсужда́ем рабо́ту.','My obsuzhdayem rabotu.','We talk about work.','Rozmawiamy o pracy.','Wir sprechen über die Arbeit.',13),
('hangingout-part-1-14','hangingout-part-1','Мы обсуждаем учёбу.','Мы обсужда́ем учёбу.','My obsuzhdayem uchyobu.','We talk about school.','Rozmawiamy o szkole.','Wir sprechen über die Schule.',14),
('hangingout-part-1-15','hangingout-part-1','Мы рассказываем истории.','Мы расска́зываем исто́рии.','My rasskazyvayem istorii.','We tell stories.','Opowiadamy historie.','Wir erzählen Geschichten.',15),
('hangingout-part-1-16','hangingout-part-1','Мой друг очень смешной.','Мой друг о́чень смешно́й.','Moy drug ochen smeshnoy.','My friend is very funny.','Mój przyjaciel jest bardzo zabawny.','Mein Freund ist sehr lustig.',16),
('hangingout-part-1-17','hangingout-part-1','Мы смотрим на людей.','Мы смо́трим на люде́й.','My smotrim na lyudey.','We watch people.','Obserwujemy ludzi.','Wir beobachten Leute.',17),
('hangingout-part-1-18','hangingout-part-1','Мы едим мороженое.','Мы еди́м моро́женое.','My yedim morozhenoye.','We eat ice cream.','Jemy lody.','Wir essen Eis.',18),
('hangingout-part-1-19','hangingout-part-1','Мы отдыхаем.','Мы отдыха́ем.','My otdykhayem.','We relax.','Odpoczywamy.','Wir entspannen uns.',19),
('hangingout-part-1-20','hangingout-part-1','Мы хорошо проводим время.','Мы хорошо́ прово́дим вре́мя.','My khorosho provodim vremya.','We have a good time.','Dobrze się bawimy.','Wir haben eine gute Zeit.',20),
('hangingout-part-1-21','hangingout-part-1','Мы идём в кино.','Мы идём в кино́.','My idyom v kino.','We go to the cinema.','Idziemy do kina.','Wir gehen ins Kino.',21),
('hangingout-part-1-22','hangingout-part-1','Фильм очень интересный.','Фильм о́чень интере́сный.','Film ochen interesnyy.','The movie is very interesting.','Film jest bardzo interesujący.','Der Film ist sehr interessant.',22),
('hangingout-part-1-23','hangingout-part-1','Мы покупаем билеты.','Мы покупа́ем биле́ты.','My pokupayem bilety.','We buy tickets.','Kupujemy bilety.','Wir kaufen Tickets.',23),
('hangingout-part-1-24','hangingout-part-1','Мы сидим рядом.','Мы сиди́м ря́дом.','My sidim ryadom.','We sit next to each other.','Siedzimy obok siebie.','Wir sitzen nebeneinander.',24),
('hangingout-part-1-25','hangingout-part-1','После фильма мы обсуждаем его.','По́сле фи́льма мы обсужда́ем его́.','Posle filma my obsuzhdayem yego.','After the movie, we talk about it.','Po filmie rozmawiamy o nim.','Nach dem Film sprechen wir darüber.',25),
('hangingout-part-1-26','hangingout-part-1','Мы играем в настольные игры.','Мы игра́ем в насто́льные и́гры.','My igrayem v nastolnye igry.','We play board games.','Gramy w gry planszowe.','Wir spielen Brettspiele.',26),
('hangingout-part-1-27','hangingout-part-1','Мой друг выигрывает.','Мой друг выи́грывает.','Moy drug vyigryvayet.','My friend wins.','Mój przyjaciel wygrywa.','Mein Freund gewinnt.',27),
('hangingout-part-1-28','hangingout-part-1','Мы снова играем.','Мы сно́ва игра́ем.','My snova igrayem.','We play again.','Gramy ponownie.','Wir spielen noch einmal.',28),
('hangingout-part-1-29','hangingout-part-1','Мы слушаем музыку.','Мы слу́шаем му́зыку.','My slushayem muzyku.','We listen to music.','Słuchamy muzyki.','Wir hören Musik.',29),
('hangingout-part-1-30','hangingout-part-1','Мне нравится эта песня.','Мне нра́вится э́та пе́сня.','Mne nravitsya eta pesnya.','I like this song.','Podoba mi się ta piosenka.','Ich mag dieses Lied.',30),
('hangingout-part-1-31','hangingout-part-1','Мы поём вместе.','Мы поём вме́сте.','My poyom vmeste.','We sing together.','Śpiewamy razem.','Wir singen zusammen.',31),
('hangingout-part-1-32','hangingout-part-1','Мы идём в торговый центр.','Мы идём в торго́вый це́нтр.','My idyom v torgovyy tsentr.','We go to the shopping mall.','Idziemy do centrum handlowego.','Wir gehen ins Einkaufszentrum.',32),
('hangingout-part-1-33','hangingout-part-1','Мы смотрим магазины.','Мы смо́трим магази́ны.','My smotrim magaziny.','We look around the shops.','Oglądamy sklepy.','Wir schauen uns die Geschäfte an.',33),
('hangingout-part-1-34','hangingout-part-1','Я ничего не покупаю.','Я ничего́ не покупа́ю.','Ya nichego ne pokupayu.','I do not buy anything.','Nic nie kupuję.','Ich kaufe nichts.',34),
('hangingout-part-1-35','hangingout-part-1','Мы просто гуляем.','Мы про́сто гуля́ем.','My prosto gulyayem.','We are just hanging out.','Po prostu spędzamy razem czas.','Wir hängen einfach zusammen ab.',35),
('hangingout-part-1-36','hangingout-part-1','Мы идём в ресторан.','Мы идём в рестора́н.','My idyom v restoran.','We go to a restaurant.','Idziemy do restauracji.','Wir gehen in ein Restaurant.',36),
('hangingout-part-1-37','hangingout-part-1','Мы заказываем еду.','Мы зака́зываем еду́.','My zakazyvayem yedu.','We order food.','Zamawiamy jedzenie.','Wir bestellen Essen.',37),
('hangingout-part-1-38','hangingout-part-1','Еда очень вкусная.','Еда́ о́чень вку́сная.','Yeda ochen vkusnaya.','The food is delicious.','Jedzenie jest pyszne.','Das Essen ist lecker.',38),
('hangingout-part-1-39','hangingout-part-1','Мы делимся едой.','Мы де́лимся едо́й.','My delimsya yedoy.','We share food.','Dzielimy się jedzeniem.','Wir teilen das Essen.',39),
('hangingout-part-1-40','hangingout-part-1','Мы говорим о путешествиях.','Мы говори́м о путеше́ствиях.','My govorim o puteshestviyakh.','We talk about traveling.','Rozmawiamy o podróżach.','Wir sprechen über Reisen.',40),
('hangingout-part-1-41','hangingout-part-1','Мы планируем отпуск.','Мы плани́руем о́тпуск.','My planiruyem otpusk.','We plan a vacation.','Planujemy wakacje.','Wir planen einen Urlaub.',41),
('hangingout-part-1-42','hangingout-part-1','Мы встречаем новых людей.','Мы встреча́ем но́вых люде́й.','My vstrechayem novykh lyudey.','We meet new people.','Poznajemy nowych ludzi.','Wir lernen neue Leute kennen.',42),
('hangingout-part-1-43','hangingout-part-1','Они очень дружелюбные.','Они́ о́чень дружелю́бные.','Oni ochen druzhelyubnye.','They are very friendly.','Są bardzo przyjaźni.','Sie sind sehr freundlich.',43),
('hangingout-part-1-44','hangingout-part-1','Мы обмениваемся номерами телефонов.','Мы обме́ниваемся номера́ми телефо́нов.','My obmenivayemsya nomerami telefonov.','We exchange phone numbers.','Wymieniamy się numerami telefonów.','Wir tauschen Telefonnummern aus.',44),
('hangingout-part-1-45','hangingout-part-1','Мы остаёмся на связи.','Мы остаёмся на свя́зи.','My ostayomsya na svyazi.','We stay in touch.','Pozostajemy w kontakcie.','Wir bleiben in Kontakt.',45),
('hangingout-part-1-46','hangingout-part-1','Мы делаем селфи.','Мы де́лаем се́лфи.','My delayem selfi.','We take a selfie.','Robimy selfie.','Wir machen ein Selfie.',46),
('hangingout-part-1-47','hangingout-part-1','Фотография получилась хорошей.','Фотогра́фия получи́лась хоро́шей.','Fotografiya poluchilas khoroshey.','The photo turned out well.','Zdjęcie wyszło dobrze.','Das Foto ist gut geworden.',47),
('hangingout-part-1-48','hangingout-part-1','Мы публикуем её в интернете.','Мы публику́ем её в интерне́те.','My publikuyem yeyo v internete.','We post it online.','Publikujemy je w internecie.','Wir posten es online.',48),
('hangingout-part-1-49','hangingout-part-1','Мы получаем много лайков.','Мы получа́ем мно́го ла́йков.','My poluchayem mnogo laykov.','We get many likes.','Dostajemy dużo polubień.','Wir bekommen viele Likes.',49),
('hangingout-part-1-50','hangingout-part-1','Это был отличный вечер.','Э́то был отли́чный ве́чер.','Eto byl otlichnyy vecher.','It was a great evening.','To był świetny wieczór.','Es war ein toller Abend.',50)
ON CONFLICT (id) DO UPDATE SET list_id=EXCLUDED.list_id, ru=EXCLUDED.ru, ru_stressed=EXCLUDED.ru_stressed, translit=EXCLUDED.translit, en=EXCLUDED.en, pl=EXCLUDED.pl, de=EXCLUDED.de, sort_order=EXCLUDED.sort_order;
