#!/usr/bin/env python3
"""Generate missing B1/B2 sentence JSON files. Each entry: [ru, ruStressed, translit, en]."""
import json, os, sys

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "data", "sentences")

PARTS = {
    # ---------------- B1 Part 1: Opinions, feelings, complex thoughts ----------------
    "b1-part-1": [
        ["Я думаю, что эта книга очень интересная.", "Я ду́маю, что э́та кни́га о́чень интере́сная.", "Ya dumayu, chto eta kniga ochen interesnaya.", "I think this book is very interesting."],
        ["По моему мнению, спорт необходим для здоровья.", "По моему́ мне́нию, спорт необходи́м для здоро́вья.", "Po moemu mneniyu, sport neobkhodim dlya zdorovya.", "In my opinion, sport is essential for health."],
        ["Мне кажется, что он прав.", "Мне ка́жется, что он прав.", "Mne kazhetsya, chto on prav.", "It seems to me that he is right."],
        ["Я считаю, что нужно больше читать.", "Я счита́ю, что ну́жно бо́льше чита́ть.", "Ya schitayu, chto nuzhno bolshe chitat.", "I believe we need to read more."],
        ["Честно говоря, мне не нравится эта идея.", "Че́стно говоря́, мне не нра́вится э́та иде́я.", "Chestno govorya, mne ne nravitsya eta ideya.", "Honestly, I don't like this idea."],
        ["С одной стороны, это удобно, с другой — дорого.", "С одно́й стороны́, э́то удо́бно, с друго́й — до́рого.", "S odnoy storony, eto udobno, s drugoy — dorogo.", "On one hand it's convenient, on the other — expensive."],
        ["Я полностью согласен с тобой.", "Я по́лностью согла́сен с тобо́й.", "Ya polnostyu soglasen s toboy.", "I completely agree with you."],
        ["Я не совсем согласна с этой точкой зрения.", "Я не совсе́м согла́сна с э́той то́чкой зре́ния.", "Ya ne sovsem soglasna s etoy tochkoy zreniya.", "I don't quite agree with this point of view."],
        ["По-моему, это лучший фильм года.", "По-мо́ему, э́то лу́чший фильм го́да.", "Po-moemu, eto luchshiy film goda.", "I think it's the best film of the year."],
        ["Мне жаль, что мы не увиделись.", "Мне жаль, что мы не уви́делись.", "Mne zhal, chto my ne uvidelis.", "I'm sorry we didn't meet."],
        ["Я рад, что ты пришёл.", "Я рад, что ты пришёл.", "Ya rad, chto ty prishyol.", "I'm glad that you came."],
        ["Я расстроен из-за плохих новостей.", "Я расстро́ен и́з-за плохи́х новосте́й.", "Ya rasstroen iz-za plokhikh novostey.", "I'm upset because of bad news."],
        ["Меня это очень удивило.", "Меня́ э́то о́чень удиви́ло.", "Menya eto ochen udivilo.", "That surprised me very much."],
        ["Я боюсь, что мы опоздаем.", "Я бою́сь, что мы опозда́ем.", "Ya boyus, chto my opozdaem.", "I'm afraid we'll be late."],
        ["Я надеюсь, что всё будет хорошо.", "Я наде́юсь, что всё бу́дет хорошо́.", "Ya nadeyus, chto vsyo budet khorosho.", "I hope everything will be fine."],
        ["Я уверен, что мы найдём решение.", "Я уве́рен, что мы найдём реше́ние.", "Ya uveren, chto my naydyom reshenie.", "I'm sure we'll find a solution."],
        ["Я сомневаюсь, что он придёт вовремя.", "Я сомнева́юсь, что он придёт во́время.", "Ya somnevayus, chto on pridyot vovremya.", "I doubt he'll come on time."],
        ["Мне трудно принять это решение.", "Мне тру́дно приня́ть э́то реше́ние.", "Mne trudno prinyat eto reshenie.", "It's hard for me to make this decision."],
        ["Я не могу понять, почему он так поступил.", "Я не могу́ поня́ть, почему́ он так поступи́л.", "Ya ne mogu ponyat, pochemu on tak postupil.", "I can't understand why he acted that way."],
        ["Это меня очень злит.", "Э́то меня́ о́чень злит.", "Eto menya ochen zlit.", "This makes me very angry."],
        ["Я скучаю по родителям.", "Я скуча́ю по роди́телям.", "Ya skuchayu po roditelyam.", "I miss my parents."],
        ["Я горжусь своими успехами.", "Я горжу́сь свои́ми успе́хами.", "Ya gorzhus svoimi uspekhami.", "I'm proud of my achievements."],
        ["Мне стыдно за свои слова.", "Мне сты́дно за свои́ слова́.", "Mne stydno za svoi slova.", "I'm ashamed of my words."],
        ["Я завидую её таланту.", "Я зави́дую её тала́нту.", "Ya zaviduyu eyo talantu.", "I envy her talent."],
        ["Я благодарен тебе за помощь.", "Я благода́рен тебе́ за по́мощь.", "Ya blagodaren tebe za pomoshch.", "I'm grateful to you for help."],
        ["Мне всё равно, что они скажут.", "Мне всё равно́, что они́ ска́жут.", "Mne vsyo ravno, chto oni skazhut.", "I don't care what they'll say."],
        ["Я волнуюсь перед экзаменом.", "Я волну́юсь пе́ред экза́меном.", "Ya volnuyus pered ekzamenom.", "I'm worried before the exam."],
        ["Я не ожидал такого ответа.", "Я не ожида́л тако́го отве́та.", "Ya ne ozhidal takogo otveta.", "I didn't expect such an answer."],
        ["Это зависит от обстоятельств.", "Э́то зави́сит от обстоя́тельств.", "Eto zavisit ot obstoyatelstv.", "It depends on the circumstances."],
        ["Возможно, ты прав.", "Возмо́жно, ты прав.", "Vozmozhno, ty prav.", "Possibly you are right."],
        ["Скорее всего, завтра будет дождь.", "Скоре́е всего́, за́втра бу́дет дождь.", "Skoree vsego, zavtra budet dozhd.", "Most likely, it will rain tomorrow."],
        ["Вряд ли мы успеем закончить.", "Вряд ли мы успе́ем зако́нчить.", "Vryad li my uspeem zakonchit.", "We are unlikely to finish in time."],
        ["Я хотел бы поделиться своим мнением.", "Я хоте́л бы подели́ться свои́м мне́нием.", "Ya khotel by podelitsya svoim mneniem.", "I would like to share my opinion."],
        ["Каждый имеет право на свою точку зрения.", "Ка́ждый име́ет пра́во на свою́ то́чку зре́ния.", "Kazhdyy imeet pravo na svoyu tochku zreniya.", "Everyone has the right to their own point of view."],
        ["Я согласна, но с одной оговоркой.", "Я согла́сна, но с одно́й огово́ркой.", "Ya soglasna, no s odnoy ogovorkoy.", "I agree, but with one reservation."],
        ["Это очень спорный вопрос.", "Э́то о́чень спо́рный вопро́с.", "Eto ochen spornyy vopros.", "This is a very controversial question."],
        ["Мне нравится твой подход к проблеме.", "Мне нра́вится твой подхо́д к пробле́ме.", "Mne nravitsya tvoy podkhod k probleme.", "I like your approach to the problem."],
        ["Я не вижу в этом ничего плохого.", "Я не ви́жу в э́том ничего́ плохо́го.", "Ya ne vizhu v etom nichego plokhogo.", "I don't see anything wrong with that."],
        ["Это вызывает у меня смешанные чувства.", "Э́то вызыва́ет у меня́ сме́шанные чу́вства.", "Eto vyzyvaet u menya smeshannye chuvstva.", "It evokes mixed feelings in me."],
        ["Я долго думал над этим вопросом.", "Я до́лго ду́мал над э́тим вопро́сом.", "Ya dolgo dumal nad etim voprosom.", "I thought about this question for a long time."],
        ["Меня вдохновляет его пример.", "Меня́ вдохновля́ет его́ приме́р.", "Menya vdokhnovlyaet ego primer.", "His example inspires me."],
        ["Я чувствую себя усталым после работы.", "Я чу́вствую себя́ уста́лым по́сле рабо́ты.", "Ya chuvstvuyu sebya ustalym posle raboty.", "I feel tired after work."],
        ["Это меня глубоко тронуло.", "Э́то меня́ глубоко́ тро́нуло.", "Eto menya gluboko tronulo.", "This deeply touched me."],
        ["Я разочарован результатами.", "Я разочаро́ван результа́тами.", "Ya razocharovan rezultatami.", "I'm disappointed with the results."],
        ["Мне приятно слышать твой голос.", "Мне прия́тно слы́шать твой го́лос.", "Mne priyatno slyshat tvoy golos.", "It's nice to hear your voice."],
        ["Я в восторге от спектакля.", "Я в восто́рге от спекта́кля.", "Ya v vostorge ot spektaklya.", "I'm delighted with the play."],
        ["Я ненавижу опаздывать.", "Я ненави́жу опа́здывать.", "Ya nenavizhu opazdyvat.", "I hate being late."],
        ["Мне нравится, как ты это объяснил.", "Мне нра́вится, как ты э́то объясни́л.", "Mne nravitsya, kak ty eto obyasnil.", "I like how you explained it."],
        ["Я постараюсь быть более терпеливым.", "Я постара́юсь быть бо́лее терпели́вым.", "Ya postarayus byt bolee terpelivym.", "I'll try to be more patient."],
        ["Я понимаю твои чувства.", "Я понима́ю твои́ чу́вства.", "Ya ponimayu tvoi chuvstva.", "I understand your feelings."],
        ["Мне сложно выразить это словами.", "Мне сло́жно вы́разить э́то слова́ми.", "Mne slozhno vyrazit eto slovami.", "It's hard for me to express this in words."],
        ["По правде сказать, я не знаю ответа.", "По пра́вде сказа́ть, я не зна́ю отве́та.", "Po pravde skazat, ya ne znayu otveta.", "To tell the truth, I don't know the answer."],
        ["На мой взгляд, это самое важное.", "На мой взгляд, э́то са́мое ва́жное.", "Na moy vzglyad, eto samoe vazhnoe.", "In my view, this is the most important thing."],
        ["Дело в том, что у нас мало времени.", "Де́ло в том, что у нас ма́ло вре́мени.", "Delo v tom, chto u nas malo vremeni.", "The thing is, we have little time."],
        ["К сожалению, я не могу прийти.", "К сожале́нию, я не могу́ прийти́.", "K sozhaleniyu, ya ne mogu priyti.", "Unfortunately, I can't come."],
        ["К счастью, всё закончилось хорошо.", "К сча́стью, всё зако́нчилось хорошо́.", "K schastyu, vsyo zakonchilos khorosho.", "Fortunately, everything ended well."],
        ["Я бы хотел добавить ещё одну мысль.", "Я бы хоте́л доба́вить ещё одну́ мысль.", "Ya by khotel dobavit eshchyo odnu mysl.", "I would like to add one more thought."],
        ["Это серьёзный повод для размышлений.", "Э́то серьёзный по́вод для размышле́ний.", "Eto seryoznyy povod dlya razmyshleniy.", "This is a serious reason to reflect."],
        ["Я никак не могу решиться.", "Я ника́к не могу́ реши́ться.", "Ya nikak ne mogu reshitsya.", "I just can't make up my mind."],
        ["Мне нужно подумать ещё немного.", "Мне ну́жно поду́мать ещё немно́го.", "Mne nuzhno podumat eshchyo nemnogo.", "I need to think a little more."],
        ["Я ценю твою честность.", "Я ценю́ твою́ че́стность.", "Ya tsenyu tvoyu chestnost.", "I appreciate your honesty."],
        ["Я доверяю своей интуиции.", "Я доверя́ю свое́й интуи́ции.", "Ya doveryayu svoey intuitsii.", "I trust my intuition."],
        ["Это противоречит моим принципам.", "Э́то противоре́чит мои́м при́нципам.", "Eto protivorechit moim printsipam.", "This contradicts my principles."],
        ["Я воспринимаю критику спокойно.", "Я воспринима́ю кри́тику споко́йно.", "Ya vosprinimayu kritiku spokoyno.", "I take criticism calmly."],
        ["Мне нужна твоя поддержка.", "Мне нужна́ твоя́ подде́ржка.", "Mne nuzhna tvoya podderzhka.", "I need your support."],
        ["Я готов выслушать любые предложения.", "Я гото́в вы́слушать любы́е предложе́ния.", "Ya gotov vyslushat lyubye predlozheniya.", "I'm ready to hear any suggestions."],
        ["Это меня совершенно не волнует.", "Э́то меня́ соверше́нно не волну́ет.", "Eto menya sovershenno ne volnuet.", "This doesn't worry me at all."],
        ["Я предпочитаю молчать в таких ситуациях.", "Я предпочита́ю молча́ть в таки́х ситуа́циях.", "Ya predpochitayu molchat v takikh situatsiyakh.", "I prefer to stay silent in such situations."],
        ["Мне трудно объяснить, что я чувствую.", "Мне тру́дно объясни́ть, что я чу́вствую.", "Mne trudno obyasnit, chto ya chuvstvuyu.", "It's hard for me to explain what I feel."],
        ["Я часто думаю о своём будущем.", "Я ча́сто ду́маю о своём бу́дущем.", "Ya chasto dumayu o svoyom budushchem.", "I often think about my future."],
        ["Я мечтаю путешествовать по миру.", "Я мечта́ю путеше́ствовать по ми́ру.", "Ya mechtayu puteshestvovat po miru.", "I dream of travelling around the world."],
        ["Меня раздражает шум за окном.", "Меня́ раздража́ет шум за окно́м.", "Menya razdrazhaet shum za oknom.", "The noise outside the window irritates me."],
        ["Я расстраиваюсь, когда меня не слышат.", "Я расстра́иваюсь, когда́ меня́ не слы́шат.", "Ya rasstraivayus, kogda menya ne slyshat.", "I get upset when I'm not heard."],
        ["Я благодарна судьбе за эту встречу.", "Я благода́рна судьбе́ за э́ту встре́чу.", "Ya blagodarna sudbe za etu vstrechu.", "I'm grateful to fate for this meeting."],
        ["Меня всегда привлекали иностранные языки.", "Меня́ всегда́ привлека́ли иностра́нные языки́.", "Menya vsegda privlekali inostrannye yazyki.", "I have always been drawn to foreign languages."],
        ["Я уважаю людей, которые держат слово.", "Я уважа́ю люде́й, кото́рые де́ржат сло́во.", "Ya uvazhayu lyudey, kotorye derzhat slovo.", "I respect people who keep their word."],
        ["Я считаю, что честность важнее всего.", "Я счита́ю, что че́стность важне́е всего́.", "Ya schitayu, chto chestnost vazhnee vsego.", "I think honesty is more important than anything."],
        ["Иногда мне хочется побыть одному.", "Иногда́ мне хо́чется побы́ть одному́.", "Inogda mne khochetsya pobyt odnomu.", "Sometimes I want to be alone."],
        ["Я устал от постоянных споров.", "Я уста́л от постоя́нных спо́ров.", "Ya ustal ot postoyannykh sporov.", "I'm tired of constant arguments."],
        ["Мне нравится наблюдать за людьми.", "Мне нра́вится наблюда́ть за людьми́.", "Mne nravitsya nablyudat za lyudmi.", "I like observing people."],
        ["Я редко жалуюсь на жизнь.", "Я ре́дко жа́луюсь на жизнь.", "Ya redko zhaluyus na zhizn.", "I rarely complain about life."],
        ["Я стараюсь видеть в людях хорошее.", "Я стара́юсь ви́деть в лю́дях хоро́шее.", "Ya starayus videt v lyudyakh khoroshee.", "I try to see the good in people."],
        ["Меня поражает её доброта.", "Меня́ поража́ет её доброта́.", "Menya porazhaet eyo dobrota.", "Her kindness amazes me."],
        ["Я обижен на его слова.", "Я оби́жен на его́ слова́.", "Ya obizhen na ego slova.", "I'm hurt by his words."],
        ["Мне жалко, что так получилось.", "Мне жа́лко, что так получи́лось.", "Mne zhalko, chto tak poluchilos.", "I'm sorry it turned out this way."],
        ["Я переживаю за свою семью.", "Я пережива́ю за свою́ семью́.", "Ya perezhivayu za svoyu semyu.", "I worry about my family."],
        ["Я искренне рад твоему успеху.", "Я и́скренне рад твоему́ успе́ху.", "Ya iskrenne rad tvoemu uspekhu.", "I'm sincerely glad of your success."],
        ["Это не имеет для меня значения.", "Э́то не име́ет для меня́ значе́ния.", "Eto ne imeet dlya menya znacheniya.", "This has no significance for me."],
        ["Мне приходится с этим мириться.", "Мне прихо́дится с э́тим мири́ться.", "Mne prikhoditsya s etim miritsya.", "I have to put up with this."],
        ["Я постоянно сомневаюсь в себе.", "Я постоя́нно сомнева́юсь в себе́.", "Ya postoyanno somnevayus v sebe.", "I constantly doubt myself."],
        ["Я чувствую себя свободным здесь.", "Я чу́вствую себя́ свобо́дным здесь.", "Ya chuvstvuyu sebya svobodnym zdes.", "I feel free here."],
        ["Меня вдохновляют истории успеха.", "Меня́ вдохновля́ют исто́рии успе́ха.", "Menya vdokhnovlyayut istorii uspekha.", "Success stories inspire me."],
        ["Я воспринимаю это как вызов.", "Я воспринима́ю э́то как вы́зов.", "Ya vosprinimayu eto kak vyzov.", "I see this as a challenge."],
        ["Я не люблю говорить о политике.", "Я не люблю́ говори́ть о поли́тике.", "Ya ne lyublyu govorit o politike.", "I don't like talking about politics."],
        ["Мне сложно отказать друзьям.", "Мне сло́жно отказа́ть друзья́м.", "Mne slozhno otkazat druzyam.", "It's hard for me to refuse friends."],
        ["Я считаю, что мы должны помогать другим.", "Я счита́ю, что мы должны́ помога́ть други́м.", "Ya schitayu, chto my dolzhny pomogat drugim.", "I think we should help others."],
        ["Я часто меняю своё мнение.", "Я ча́сто меня́ю своё мне́ние.", "Ya chasto menyayu svoyo mnenie.", "I often change my opinion."],
        ["Мне важно мнение близких людей.", "Мне ва́жно мне́ние бли́зких люде́й.", "Mne vazhno mnenie blizkikh lyudey.", "The opinion of close people matters to me."],
        ["Я переоценил свои силы.", "Я переоцени́л свои́ си́лы.", "Ya pereotsenil svoi sily.", "I overestimated my strength."],
        ["Я стараюсь не принимать поспешных решений.", "Я стара́юсь не принима́ть поспе́шных реше́ний.", "Ya starayus ne prinimat pospeshnykh resheniy.", "I try not to make hasty decisions."],
        ["Иногда лучше промолчать.", "Иногда́ лу́чше промолча́ть.", "Inogda luchshe promolchat.", "Sometimes it's better to keep silent."],
        ["Я понял, что был неправ.", "Я по́нял, что был непра́в.", "Ya ponyal, chto byl neprav.", "I realized I was wrong."],
    ],

    # ---------------- B2 Part 2: News, environment, formal speech ----------------
    "b2-part-2": [
        ["Согласно последним данным, уровень безработицы снизился.", "Согла́сно после́дним да́нным, у́ровень безрабо́тицы сни́зился.", "Soglasno poslednim dannym, uroven bezrabotitsy snizilsya.", "According to the latest data, the unemployment rate has decreased."],
        ["Правительство объявило о новых экономических реформах.", "Прави́тельство объяви́ло о но́вых экономи́ческих рефо́рмах.", "Pravitelstvo obyavilo o novykh ekonomicheskikh reformakh.", "The government announced new economic reforms."],
        ["Учёные предупреждают о последствиях глобального потепления.", "Учёные предупрежда́ют о после́дствиях глоба́льного потепле́ния.", "Uchyonye preduprezhdayut o posledstviyakh globalnogo potepleniya.", "Scientists warn about the consequences of global warming."],
        ["В стране введён режим чрезвычайной ситуации.", "В стране́ введён режи́м чрезвыча́йной ситуа́ции.", "V strane vvedyon rezhim chrezvychaynoy situatsii.", "A state of emergency has been declared in the country."],
        ["Президент выступил с обращением к нации.", "Президе́нт вы́ступил с обраще́нием к на́ции.", "Prezident vystupil s obrashcheniem k natsii.", "The president addressed the nation."],
        ["Загрязнение воздуха достигло критического уровня.", "Загрязне́ние во́здуха дости́гло крити́ческого у́ровня.", "Zagryaznenie vozdukha dostiglo kriticheskogo urovnya.", "Air pollution has reached a critical level."],
        ["Эксперты прогнозируют рост цен на энергоносители.", "Экспе́рты прогнози́руют рост цен на энергоноси́тели.", "Eksperty prognoziruyut rost tsen na energonositeli.", "Experts forecast a rise in energy prices."],
        ["Парламент принял закон в первом чтении.", "Парла́мент при́нял зако́н в пе́рвом чте́нии.", "Parlament prinyal zakon v pervom chtenii.", "Parliament passed the law in the first reading."],
        ["Делегации обсудили вопросы двустороннего сотрудничества.", "Делега́ции обсуди́ли вопро́сы двусторо́ннего сотру́дничества.", "Delegatsii obsudili voprosy dvustoronnego sotrudnichestva.", "The delegations discussed issues of bilateral cooperation."],
        ["Министр выразил озабоченность сложившейся ситуацией.", "Мини́стр вы́разил озабо́ченность сложи́вшейся ситуа́цией.", "Ministr vyrazil ozabochennost slozhivsheysya situatsiey.", "The minister expressed concern over the current situation."],
        ["Введены санкции против ряда компаний.", "Введены́ са́нкции про́тив ря́да компа́ний.", "Vvedeny sanktsii protiv ryada kompaniy.", "Sanctions have been imposed on a number of companies."],
        ["Площадь лесных пожаров продолжает расти.", "Пло́щадь лесны́х пожа́ров продолжа́ет расти́.", "Ploshchad lesnykh pozharov prodolzhaet rasti.", "The area of forest fires continues to grow."],
        ["В результате наводнения пострадали тысячи людей.", "В результа́те наводне́ния пострада́ли ты́сячи люде́й.", "V rezultate navodneniya postradali tysyachi lyudey.", "Thousands of people were affected by the flood."],
        ["Гуманитарная помощь была доставлена в зону бедствия.", "Гуманита́рная по́мощь была́ доста́влена в зо́ну бе́дствия.", "Gumanitarnaya pomoshch byla dostavlena v zonu bedstviya.", "Humanitarian aid was delivered to the disaster zone."],
        ["Стороны достигли соглашения о прекращении огня.", "Сто́роны дости́гли соглаше́ния о прекраще́нии огня́.", "Storony dostigli soglasheniya o prekrashchenii ognya.", "The parties reached a ceasefire agreement."],
        ["Курс национальной валюты значительно упал.", "Курс национа́льной валю́ты значи́тельно упа́л.", "Kurs natsionalnoy valyuty znachitelno upal.", "The national currency's rate has fallen significantly."],
        ["В крупных городах ужесточили карантинные меры.", "В кру́пных города́х ужесточи́ли каранти́нные ме́ры.", "V krupnykh gorodakh uzhestochili karantinnye mery.", "Quarantine measures have been tightened in major cities."],
        ["Учёные обнаружили новый вид бактерий.", "Учёные обнару́жили но́вый вид бакте́рий.", "Uchyonye obnaruzhili novyy vid bakteriy.", "Scientists have discovered a new species of bacteria."],
        ["Запуск спутника был отложен из-за погодных условий.", "За́пуск спу́тника был отло́жен и́з-за пого́дных усло́вий.", "Zapusk sputnika byl otlozhen iz-za pogodnykh usloviy.", "The satellite launch was postponed due to weather conditions."],
        ["Объём промышленного производства увеличился на пять процентов.", "Объём промы́шленного произво́дства увели́чился на пять проце́нтов.", "Obyom promyshlennogo proizvodstva uvelichilsya na pyat protsentov.", "Industrial output increased by five percent."],
        ["Государственный долг превысил отметку в триллион.", "Госуда́рственный долг превы́сил отме́тку в триллио́н.", "Gosudarstvennyy dolg prevysil otmetku v trillion.", "The national debt exceeded one trillion."],
        ["Возобновляемая энергетика становится всё более доступной.", "Возобновля́емая энерге́тика стано́вится всё бо́лее досту́пной.", "Vozobnovlyaemaya energetika stanovitsya vsyo bolee dostupnoy.", "Renewable energy is becoming more accessible."],
        ["Власти ввели запрет на использование пластиковых пакетов.", "Вла́сти ввели́ запре́т на испо́льзование пластико́вых паке́тов.", "Vlasti vveli zapret na ispolzovanie plastikovykh paketov.", "Authorities introduced a ban on plastic bags."],
        ["Сокращение выбросов углерода — приоритет международной политики.", "Сокраще́ние вы́бросов углеро́да — приорите́т междунаро́дной поли́тики.", "Sokrashchenie vybrosov ugleroda — prioritet mezhdunarodnoy politiki.", "Reducing carbon emissions is a priority of international policy."],
        ["Многие виды животных находятся под угрозой исчезновения.", "Мно́гие ви́ды живо́тных нахо́дятся под угро́зой исчезнове́ния.", "Mnogie vidy zhivotnykh nakhodyatsya pod ugrozoy ischeznoveniya.", "Many animal species are under threat of extinction."],
        ["Учёные разработали новый метод очистки воды.", "Учёные разрабо́тали но́вый ме́тод очи́стки воды́.", "Uchyonye razrabotali novyy metod ochistki vody.", "Scientists have developed a new method of water purification."],
        ["Переход на электромобили снизит зависимость от нефти.", "Перехо́д на электромоби́ли сни́зит зави́симость от не́фти.", "Perekhod na elektromobili snizit zavisimost ot nefti.", "The shift to electric cars will reduce oil dependence."],
        ["Тающие ледники угрожают прибрежным городам.", "Та́ющие ледники́ угрожа́ют прибре́жным города́м.", "Tayushchie ledniki ugrozhayut pribrezhnym gorodam.", "Melting glaciers threaten coastal cities."],
        ["Необходимо принимать меры по защите окружающей среды.", "Необходи́мо принима́ть ме́ры по защи́те окружа́ющей среды́.", "Neobkhodimo prinimat mery po zashchite okruzhayushchey sredy.", "It is necessary to take measures to protect the environment."],
        ["Уровень моря поднимается с каждым годом.", "У́ровень мо́ря поднима́ется с ка́ждым го́дом.", "Uroven morya podnimaetsya s kazhdym godom.", "Sea level rises every year."],
        ["Вырубка лесов наносит непоправимый вред природе.", "Вы́рубка лесо́в наво́сит непоправи́мый вред приро́де.", "Vyrubka lesov nanosit nepopravimyy vred prirode.", "Deforestation does irreparable damage to nature."],
        ["Программа переработки отходов даёт первые результаты.", "Програ́мма перерабо́тки отхо́дов даёт пе́рвые результа́ты.", "Programma pererabotki otkhodov dayot pervye rezultaty.", "The recycling programme is yielding first results."],
        ["Загрязнение океана пластиком стало глобальной проблемой.", "Загрязне́ние океа́на пла́стиком ста́ло глоба́льной пробле́мой.", "Zagryaznenie okeana plastikom stalo globalnoy problemoy.", "Ocean plastic pollution has become a global problem."],
        ["Биоразнообразие планеты сокращается тревожными темпами.", "Биоразнообра́зие плане́ты сокраща́ется трево́жными те́мпами.", "Bioraznoobrazie planety sokrashchaetsya trevozhnymi tempami.", "The planet's biodiversity is shrinking at alarming rates."],
        ["Конференция по климату пройдёт в следующем месяце.", "Конфере́нция по кли́мату пройдёт в сле́дующем ме́сяце.", "Konferentsiya po klimatu proydyot v sleduyushchem mesyatse.", "The climate conference will take place next month."],
        ["В пресс-релизе компания подтвердила свою позицию.", "В пресс-рели́зе компа́ния подтверди́ла свою́ пози́цию.", "V press-relize kompaniya podtverdila svoyu pozitsiyu.", "In the press release, the company confirmed its position."],
        ["Доклад был представлен на пленарном заседании.", "Докла́д был предста́влен на плена́рном заседа́нии.", "Doklad byl predstavlen na plenarnom zasedanii.", "The report was presented at the plenary session."],
        ["Уважаемые коллеги, позвольте начать заседание.", "Уважа́емые колле́ги, позво́льте нача́ть заседа́ние.", "Uvazhaemye kollegi, pozvolte nachat zasedanie.", "Dear colleagues, allow me to open the session."],
        ["Прошу вас обратить внимание на следующий пункт.", "Прошу́ вас обрати́ть внима́ние на сле́дующий пункт.", "Proshu vas obratit vnimanie na sleduyushchiy punkt.", "I ask you to pay attention to the next point."],
        ["Хотелось бы подчеркнуть важность этого вопроса.", "Хоте́лось бы подчеркну́ть ва́жность э́того вопро́са.", "Khotelos by podcherknut vazhnost etogo voprosa.", "I would like to underline the importance of this issue."],
        ["Подводя итоги, можно сделать следующие выводы.", "Подводя́ ито́ги, мо́жно сде́лать сле́дующие вы́воды.", "Podvodya itogi, mozhno sdelat sleduyushchie vyvody.", "To sum up, the following conclusions can be drawn."],
        ["Согласно официальной статистике, ситуация улучшается.", "Согла́сно официа́льной стати́стике, ситуа́ция улучша́ется.", "Soglasno ofitsialnoy statistike, situatsiya uluchshaetsya.", "According to official statistics, the situation is improving."],
        ["Данное решение требует тщательного обсуждения.", "Да́нное реше́ние тре́бует тща́тельного обсужде́ния.", "Dannoe reshenie trebuet tshchatelnogo obsuzhdeniya.", "This decision requires thorough discussion."],
        ["Позвольте выразить благодарность всем участникам.", "Позво́льте вы́разить благода́рность всем уча́стникам.", "Pozvolte vyrazit blagodarnost vsem uchastnikam.", "Allow me to express gratitude to all participants."],
        ["В заключение хочу отметить заслуги команды.", "В заключе́ние хочу́ отме́тить заслу́ги кома́нды.", "V zaklyuchenie khochu otmetit zaslugi komandy.", "In conclusion, I want to note the team's merits."],
        ["Вопрос остаётся открытым и требует дальнейшего изучения.", "Вопро́с остаётся откры́тым и тре́бует дальне́йшего изуче́ния.", "Vopros ostayotsya otkrytym i trebuet dalneyshego izucheniya.", "The question remains open and requires further study."],
        ["Стороны выразили готовность к продолжению диалога.", "Сто́роны вы́разили гото́вность к продолже́нию диало́га.", "Storony vyrazili gotovnost k prodolzheniyu dialoga.", "The parties expressed readiness to continue dialogue."],
        ["В средствах массовой информации появились противоречивые сообщения.", "В сре́дствах ма́ссовой информа́ции появи́лись противоречи́вые сообще́ния.", "V sredstvakh massovoy informatsii poyavilis protivorechivye soobshcheniya.", "Conflicting reports appeared in the mass media."],
        ["По данным независимых источников, информация подтверждается.", "По да́нным незави́симых исто́чников, информа́ция подтвержда́ется.", "Po dannym nezavisimykh istochnikov, informatsiya podtverzhdaetsya.", "According to independent sources, the information is confirmed."],
        ["Эта инициатива получила широкую общественную поддержку.", "Э́та инициати́ва получи́ла широ́кую обще́ственную подде́ржку.", "Eta initsiativa poluchila shirokuyu obshchestvennuyu podderzhku.", "This initiative has received wide public support."],
        ["Реформа здравоохранения вступит в силу с января.", "Рефо́рма здравоохране́ния всту́пит в си́лу с января́.", "Reforma zdravookhraneniya vstupit v silu s yanvarya.", "The healthcare reform will take effect in January."],
        ["Расследование инцидента продолжается под контролем прокуратуры.", "Рассле́дование инциде́нта продолжа́ется под контро́лем прокурату́ры.", "Rassledovanie intsidenta prodolzhaetsya pod kontrolem prokuratury.", "The investigation of the incident continues under the prosecutor's supervision."],
        ["Эксперты призывают к консолидации усилий.", "Экспе́рты призыва́ют к консолида́ции уси́лий.", "Eksperty prizyvayut k konsolidatsii usiliy.", "Experts call for the consolidation of efforts."],
        ["Очередное заседание комитета состоится в пятницу.", "Очередно́е заседа́ние комите́та состои́тся в пя́тницу.", "Ocherednoe zasedanie komiteta sostoitsya v pyatnitsu.", "The next committee meeting will take place on Friday."],
        ["Проект бюджета направлен на рассмотрение в парламент.", "Прое́кт бюдже́та напра́влен на рассмотре́ние в парла́мент.", "Proekt byudzheta napravlen na rassmotrenie v parlament.", "The draft budget has been sent to parliament for consideration."],
        ["Введение нового налога вызвало широкий резонанс.", "Введе́ние но́вого нало́га вы́звало широ́кий резона́нс.", "Vvedenie novogo naloga vyzvalo shirokiy rezonans.", "The introduction of the new tax caused wide public response."],
        ["Темпы инфляции остаются на стабильном уровне.", "Те́мпы инфля́ции остаю́тся на стаби́льном у́ровне.", "Tempy inflyatsii ostayutsya na stabilnom urovne.", "Inflation rates remain at a stable level."],
        ["Программа поддержки малого бизнеса будет продлена.", "Програ́мма подде́ржки ма́лого би́знеса бу́дет продлена́.", "Programma podderzhki malogo biznesa budet prodlena.", "The small business support programme will be extended."],
        ["Министерство опубликовало официальный отчёт.", "Министе́рство опубликова́ло официа́льный отчёт.", "Ministerstvo opublikovalo ofitsialnyy otchyot.", "The ministry has published an official report."],
        ["Согласно прогнозу, экономика вырастет на три процента.", "Согла́сно прогно́зу, эконо́мика вы́растет на три проце́нта.", "Soglasno prognozu, ekonomika vyrastet na tri protsenta.", "According to the forecast, the economy will grow by three percent."],
        ["Объёмы экспорта достигли рекордных показателей.", "Объёмы экспо́рта дости́гли реко́рдных показа́телей.", "Obyomy eksporta dostigli rekordnykh pokazateley.", "Export volumes have reached record figures."],
        ["Принятие новых стандартов положительно скажется на отрасли.", "Приня́тие но́вых станда́ртов положи́тельно ска́жется на о́трасли.", "Prinyatie novykh standartov polozhitelno skazhetsya na otrasli.", "Adoption of new standards will positively affect the industry."],
        ["Сегодня в столице открылась международная выставка.", "Сего́дня в столи́це откры́лась междунаро́дная вы́ставка.", "Segodnya v stolitse otkrylas mezhdunarodnaya vystavka.", "An international exhibition opened in the capital today."],
        ["Глава государства поздравил граждан с национальным праздником.", "Глава́ госуда́рства поздра́вил гра́ждан с национа́льным пра́здником.", "Glava gosudarstva pozdravil grazhdan s natsionalnym prazdnikom.", "The head of state congratulated citizens on the national holiday."],
        ["В ходе пресс-конференции были озвучены важные заявления.", "В хо́де пресс-конфере́нции бы́ли озву́чены ва́жные заявле́ния.", "V khode press-konferentsii byli ozvucheny vazhnye zayavleniya.", "Important statements were made during the press conference."],
        ["Спортсмены завоевали несколько медалей на чемпионате.", "Спортсме́ны завоева́ли не́сколько меда́лей на чемпиона́те.", "Sportsmeny zavoevali neskolko medaley na chempionate.", "The athletes won several medals at the championship."],
        ["Меры безопасности были усилены по всему городу.", "Ме́ры безопа́сности бы́ли уси́лены по всему́ го́роду.", "Mery bezopasnosti byli usileny po vsemu gorodu.", "Security measures have been strengthened throughout the city."],
        ["Решение суда вступило в законную силу.", "Реше́ние суда́ вступи́ло в зако́нную си́лу.", "Reshenie suda vstupilo v zakonnuyu silu.", "The court's decision has entered into legal force."],
        ["Транспортная инфраструктура нуждается в модернизации.", "Тра́нспортная инфраструкту́ра нужда́ется в модерниза́ции.", "Transportnaya infrastruktura nuzhdaetsya v modernizatsii.", "The transport infrastructure needs modernization."],
        ["Цифровизация экономики открывает новые возможности.", "Цифровиза́ция эконо́мики открыва́ет но́вые возмо́жности.", "Tsifrovizatsiya ekonomiki otkryvaet novye vozmozhnosti.", "Digitalisation of the economy opens new opportunities."],
        ["Развитие технологий искусственного интеллекта ускоряется.", "Разви́тие техноло́гий иску́сственного интелле́кта ускоря́ется.", "Razvitie tekhnologiy iskusstvennogo intellekta uskoryaetsya.", "The development of AI technologies is accelerating."],
        ["Государство выделило средства на поддержку науки.", "Госуда́рство вы́делило сре́дства на подде́ржку нау́ки.", "Gosudarstvo vydelilo sredstva na podderzhku nauki.", "The state allocated funds to support science."],
        ["Закон направлен на защиту прав потребителей.", "Зако́н напра́влен на защи́ту прав потреби́телей.", "Zakon napravlen na zashchitu prav potrebiteley.", "The law is aimed at protecting consumer rights."],
        ["Образовательная система требует комплексных изменений.", "Образова́тельная систе́ма тре́бует ко́мплексных измене́ний.", "Obrazovatelnaya sistema trebuet kompleksnykh izmeneniy.", "The educational system requires comprehensive changes."],
        ["Президент поручил кабинету министров разработать план.", "Президе́нт поручи́л кабине́ту мини́стров разрабо́тать план.", "Prezident poruchil kabinetu ministrov razrabotat plan.", "The president instructed the cabinet to develop a plan."],
        ["Соглашение было подписано в торжественной обстановке.", "Соглаше́ние бы́ло подпи́сано в торже́ственной обстано́вке.", "Soglashenie bylo podpisano v torzhestvennoy obstanovke.", "The agreement was signed in a solemn atmosphere."],
        ["Учёные призывают сократить потребление мяса.", "Учёные призыва́ют сократи́ть потребле́ние мя́са.", "Uchyonye prizyvayut sokratit potreblenie myasa.", "Scientists urge reducing meat consumption."],
        ["Глобализация принесла как плюсы, так и минусы.", "Глобализа́ция принесла́ как плю́сы, так и ми́нусы.", "Globalizatsiya prinesla kak plyusy, tak i minusy.", "Globalisation brought both pluses and minuses."],
        ["Уровень цифрового неравенства снижается.", "У́ровень цифрово́го нера́венства снижа́ется.", "Uroven tsifrovogo neravenstva snizhaetsya.", "The level of digital inequality is decreasing."],
        ["Доступ к качественному образованию — основа развития.", "До́ступ к ка́чественному образова́нию — осно́ва разви́тия.", "Dostup k kachestvennomu obrazovaniyu — osnova razvitiya.", "Access to quality education is the foundation of development."],
        ["В долгосрочной перспективе изменения принесут пользу.", "В долгосро́чной перспекти́ве измене́ния принесу́т по́льзу.", "V dolgosrochnoy perspektive izmeneniya prinesut polzu.", "In the long term, the changes will bring benefit."],
        ["Стратегия развития рассчитана на десять лет.", "Страте́гия разви́тия рассчи́тана на де́сять лет.", "Strategiya razvitiya rasschitana na desyat let.", "The development strategy is designed for ten years."],
        ["Эффективность мер будет оценена по итогам года.", "Эффекти́вность мер бу́дет оценена́ по ито́гам го́да.", "Effektivnost mer budet otsenena po itogam goda.", "The effectiveness of measures will be assessed at the end of the year."],
        ["Решающее значение имеет международное сотрудничество.", "Реша́ющее значе́ние име́ет междунаро́дное сотру́дничество.", "Reshayushchee znachenie imeet mezhdunarodnoe sotrudnichestvo.", "International cooperation is of decisive importance."],
        ["Ключевые показатели свидетельствуют о росте.", "Ключевы́е показа́тели свиде́тельствуют о ро́сте.", "Klyuchevye pokazateli svidetelstvuyut o roste.", "Key indicators testify to growth."],
        ["Эпидемиологическая обстановка стабилизировалась.", "Эпидемиологи́ческая обстано́вка стабилизи́ровалась.", "Epidemiologicheskaya obstanovka stabilizirovalas.", "The epidemiological situation has stabilised."],
        ["В рамках проекта будут построены новые школы.", "В ра́мках прое́кта бу́дут постро́ены но́вые шко́лы.", "V ramkakh proekta budut postroeny novye shkoly.", "Within the project, new schools will be built."],
        ["Принятые меры доказали свою эффективность.", "При́нятые ме́ры доказа́ли свою́ эффекти́вность.", "Prinyatye mery dokazali svoyu effektivnost.", "The measures taken have proved their effectiveness."],
        ["Современные технологии меняют рынок труда.", "Совреме́нные техноло́гии меня́ют ры́нок труда́.", "Sovremennye tekhnologii menyayut rynok truda.", "Modern technologies are changing the labour market."],
        ["Сектор услуг демонстрирует устойчивый рост.", "Се́ктор услу́г демонстри́рует усто́йчивый рост.", "Sektor uslug demonstriruet ustoychivyy rost.", "The service sector demonstrates steady growth."],
        ["Налоговая нагрузка на бизнес будет пересмотрена.", "Нало́говая нагру́зка на би́знес бу́дет пересмо́трена.", "Nalogovaya nagruzka na biznes budet peresmotrena.", "The tax burden on business will be reviewed."],
        ["Объявлено о запуске пилотного проекта.", "Объя́влено о за́пуске пило́тного прое́кта.", "Obyavleno o zapuske pilotnogo proekta.", "A pilot project launch has been announced."],
        ["Подписан меморандум о взаимопонимании.", "Подпи́сан мемора́ндум о взаимопонима́нии.", "Podpisan memorandum o vzaimoponimanii.", "A memorandum of understanding has been signed."],
        ["Глава делегации провёл переговоры с коллегами.", "Глава́ делега́ции провёл перегово́ры с колле́гами.", "Glava delegatsii provyol peregovory s kollegami.", "The head of the delegation held talks with colleagues."],
        ["Объём инвестиций в регион увеличился вдвое.", "Объём инвести́ций в регио́н увели́чился вдво́е.", "Obyom investitsiy v region uvelichilsya vdvoe.", "The volume of investments in the region has doubled."],
        ["Ситуация на финансовых рынках остаётся напряжённой.", "Ситуа́ция на фина́нсовых ры́нках остаётся напряжённой.", "Situatsiya na finansovykh rynkakh ostayotsya napryazhyonnoy.", "The situation on financial markets remains tense."],
        ["По итогам встречи было опубликовано совместное заявление.", "По ито́гам встре́чи бы́ло опубликова́но совме́стное заявле́ние.", "Po itogam vstrechi bylo opublikovano sovmestnoe zayavlenie.", "Following the meeting, a joint statement was published."],
        ["Реализация программы потребует значительных ресурсов.", "Реализа́ция програ́ммы потре́бует значи́тельных ресу́рсов.", "Realizatsiya programmy potrebuet znachitelnykh resursov.", "Implementation of the programme will require significant resources."],
        ["Эксперты подчёркивают необходимость системного подхода.", "Экспе́рты подчёркивают необходи́мость систе́много подхо́да.", "Eksperty podchyorkivayut neobkhodimost sistemnogo podkhoda.", "Experts emphasise the need for a systemic approach."],
        ["Ожидается, что новые правила вступят в силу в следующем квартале.", "Ожида́ется, что но́вые пра́вила всту́пят в си́лу в сле́дующем кварта́ле.", "Ozhidaetsya, chto novye pravila vstupyat v silu v sleduyushchem kvartale.", "The new rules are expected to take effect next quarter."],
        ["Доклад вызвал оживлённую дискуссию среди экспертов.", "Докла́д вы́звал оживлённую диску́ссию среди́ экспе́ртов.", "Doklad vyzval ozhivlyonnuyu diskussiyu sredi ekspertov.", "The report sparked lively discussion among experts."],
    ],

    # ---------------- B2 Part 3: Idioms and colloquial expressions ----------------
    "b2-part-3": [
        ["Не вешай нос, всё будет хорошо!", "Не ве́шай нос, всё бу́дет хорошо́!", "Ne veshay nos, vsyo budet khorosho!", "Don't be sad, everything will be fine!"],
        ["Он бьёт баклуши целыми днями.", "Он бьёт баклу́ши це́лыми дня́ми.", "On byot baklushi tselymi dnyami.", "He twiddles his thumbs all day long."],
        ["Это работа спустя рукава.", "Э́то рабо́та спустя́ рукава́.", "Eto rabota spustya rukava.", "This is slipshod work."],
        ["Не за что переживать — это пустяки.", "Не за что пережива́ть — э́то пустяки́.", "Ne za chto perezhivat — eto pustyaki.", "There's nothing to worry about — it's trifles."],
        ["Он наобещал с три короба.", "Он наобеща́л с три ко́роба.", "On naobeshchal s tri koroba.", "He promised a heap of things (more than he can deliver)."],
        ["У него денег куры не клюют.", "У него́ де́нег ку́ры не клюю́т.", "U nego deneg kury ne klyuyut.", "He is rolling in money."],
        ["Это как дважды два — четыре.", "Э́то как два́жды два — четы́ре.", "Eto kak dvazhdy dva — chetyre.", "It's as simple as two times two equals four."],
        ["Не лезь на рожон!", "Не лезь на рожо́н!", "Ne lez na rozhon!", "Don't ask for trouble!"],
        ["Он держит язык за зубами.", "Он де́ржит язы́к за зуба́ми.", "On derzhit yazyk za zubami.", "He keeps his mouth shut."],
        ["Ну, ты даёшь!", "Ну, ты даёшь!", "Nu, ty dayosh!", "Wow, you're something!"],
        ["Это в одно ухо влетело, в другое вылетело.", "Э́то в одно́ у́хо влете́ло, в друго́е вы́летело.", "Eto v odno ukho vletelo, v drugoe vyletelo.", "It went in one ear and out the other."],
        ["Делать из мухи слона — его любимое занятие.", "Де́лать из му́хи слона́ — его́ люби́мое заня́тие.", "Delat iz mukhi slona — ego lyubimoe zanyatie.", "Making a mountain out of a molehill is his favourite pastime."],
        ["Мы работаем не покладая рук.", "Мы рабо́таем не покла́дая рук.", "My rabotaem ne pokladaya ruk.", "We work tirelessly."],
        ["Бабушка надвое сказала.", "Ба́бушка на́двое сказа́ла.", "Babushka nadvoe skazala.", "It's still up in the air (lit. grandma said it two ways)."],
        ["Ну, погнали!", "Ну, погна́ли!", "Nu, pognali!", "Well, let's get going!"],
        ["Он же мне всю плешь проел.", "Он же мне всю плешь прое́л.", "On zhe mne vsyu plesh proel.", "He's been nagging me to death."],
        ["Зуб даю, что это правда.", "Зуб даю́, что э́то пра́вда.", "Zub dayu, chto eto pravda.", "I swear it's true."],
        ["Что-то я туплю сегодня.", "Что́-то я туплю́ сего́дня.", "Chto-to ya tuplyu segodnya.", "I'm a bit slow today."],
        ["Это полная ерунда!", "Э́то по́лная ерунда́!", "Eto polnaya erunda!", "It's complete nonsense!"],
        ["Он влип по уши.", "Он влип по у́ши.", "On vlip po ushi.", "He got into deep trouble."],
        ["Хватит валять дурака!", "Хва́тит валя́ть дурака́!", "Khvatit valyat duraka!", "Stop fooling around!"],
        ["Я тебе позвоню, не парься.", "Я тебе́ позвоню́, не па́рься.", "Ya tebe pozvonyu, ne parsya.", "I'll call you, don't sweat it."],
        ["Это вообще не моё дело.", "Э́то вообще́ не моё де́ло.", "Eto voobshche ne moyo delo.", "It's none of my business."],
        ["Он отличный мужик.", "Он отли́чный мужи́к.", "On otlichnyy muzhik.", "He's a great guy."],
        ["Я просто в шоке от этой новости.", "Я про́сто в шо́ке от э́той но́вости.", "Ya prosto v shoke ot etoy novosti.", "I'm just shocked by this news."],
        ["Не парься, всё уладится.", "Не па́рься, всё ула́дится.", "Ne parsya, vsyo uladitsya.", "Don't stress, everything will work out."],
        ["Дело в шляпе!", "Де́ло в шля́пе!", "Delo v shlyape!", "It's in the bag!"],
        ["Он попал в самое яблочко.", "Он попа́л в са́мое я́блочко.", "On popal v samoe yablochko.", "He hit the bullseye."],
        ["Как с гуся вода.", "Как с гу́ся вода́.", "Kak s gusya voda.", "Like water off a duck's back."],
        ["Куда тебя несёт?", "Куда́ тебя́ несёт?", "Kuda tebya nesyot?", "Where on earth are you going?"],
        ["Он совсем рехнулся.", "Он совсе́м рехну́лся.", "On sovsem rekhnulsya.", "He's gone completely crazy."],
        ["Это копейки!", "Э́то копе́йки!", "Eto kopeyki!", "It's peanuts!"],
        ["Ну ты загнул!", "Ну ты загну́л!", "Nu ty zagnul!", "Now you're exaggerating!"],
        ["Я тебя умоляю!", "Я тебя́ умоля́ю!", "Ya tebya umolyayu!", "Oh, please!"],
        ["Давай по-быстрому.", "Дава́й по-бы́строму.", "Davay po-bystromu.", "Let's do it quickly."],
        ["Он любит лапшу на уши вешать.", "Он лю́бит лапшу́ на у́ши ве́шать.", "On lyubit lapshu na ushi veshat.", "He likes to pull the wool over people's eyes."],
        ["Я не в курсе, что там происходит.", "Я не в ку́рсе, что там происхо́дит.", "Ya ne v kurse, chto tam proiskhodit.", "I'm not aware of what's going on there."],
        ["Тише едешь — дальше будешь.", "Ти́ше е́дешь — да́льше бу́дешь.", "Tishe edesh — dalshe budesh.", "Slow and steady wins the race."],
        ["Без труда не выловишь и рыбку из пруда.", "Без труда́ не вы́ловишь и ры́бку из пруда́.", "Bez truda ne vylovish i rybku iz pruda.", "No pain, no gain."],
        ["В тихом омуте черти водятся.", "В ти́хом о́муте че́рти во́дятся.", "V tikhom omute cherti vodyatsya.", "Still waters run deep."],
        ["Не имей сто рублей, а имей сто друзей.", "Не име́й сто рубле́й, а име́й сто друзе́й.", "Ne imey sto rubley, a imey sto druzey.", "Better a hundred friends than a hundred roubles."],
        ["Цыплят по осени считают.", "Цыпля́т по о́сени счита́ют.", "Tsyplyat po oseni schitayut.", "Don't count your chickens before they hatch."],
        ["Слово — серебро, молчание — золото.", "Сло́во — серебро́, молча́ние — зо́лото.", "Slovo — serebro, molchanie — zoloto.", "Speech is silver, silence is golden."],
        ["Любишь кататься — люби и саночки возить.", "Лю́бишь ката́ться — люби́ и са́ночки вози́ть.", "Lyubish katatsya — lyubi i sanochki vozit.", "If you like riding, you must like to pull the sled."],
        ["Семь раз отмерь, один раз отрежь.", "Семь раз отме́рь, оди́н раз отре́жь.", "Sem raz otmer, odin raz otrezh.", "Measure seven times, cut once."],
        ["Не всё то золото, что блестит.", "Не всё то зо́лото, что блести́т.", "Ne vsyo to zoloto, chto blestit.", "All that glitters is not gold."],
        ["На безрыбье и рак — рыба.", "На безры́бье и рак — ры́ба.", "Na bezrybe i rak — ryba.", "In the absence of fish, a crab is also fish."],
        ["Голод не тётка.", "Го́лод не тётка.", "Golod ne tyotka.", "Hunger is no joke."],
        ["Утро вечера мудренее.", "У́тро ве́чера мудрене́е.", "Utro vechera mudrenee.", "The morning is wiser than the evening."],
        ["Старый друг лучше новых двух.", "Ста́рый друг лу́чше но́вых двух.", "Staryy drug luchshe novykh dvukh.", "An old friend is better than two new ones."],
        ["Друг познаётся в беде.", "Друг познаётся в беде́.", "Drug poznayotsya v bede.", "A friend in need is a friend indeed."],
        ["Лучше поздно, чем никогда.", "Лу́чше по́здно, чем никогда́.", "Luchshe pozdno, chem nikogda.", "Better late than never."],
        ["Терпение и труд всё перетрут.", "Терпе́ние и труд всё перетру́т.", "Terpenie i trud vsyo peretrut.", "Patience and work wear everything down."],
        ["Век живи — век учись.", "Век живи́ — век учи́сь.", "Vek zhivi — vek uchis.", "Live and learn."],
        ["Яблоко от яблони недалеко падает.", "Я́блоко от я́блони недалеко́ па́дает.", "Yabloko ot yabloni nedaleko padaet.", "The apple doesn't fall far from the tree."],
        ["Глаза боятся, а руки делают.", "Глаза́ боя́тся, а ру́ки де́лают.", "Glaza boyatsya, a ruki delayut.", "Eyes fear, but hands do."],
        ["Лес рубят — щепки летят.", "Лес ру́бят — ще́пки летя́т.", "Les rubyat — shchepki letyat.", "When chopping wood, chips fly (you can't make an omelette without breaking eggs)."],
        ["Один в поле не воин.", "Оди́н в по́ле не во́ин.", "Odin v pole ne voin.", "One man is no warrior in the field."],
        ["Слово не воробей: вылетит — не поймаешь.", "Сло́во не воробе́й: вы́летит — не пойма́ешь.", "Slovo ne vorobey: vyletit — ne poymaesh.", "A word is not a sparrow; once it flies out, you can't catch it."],
        ["Семь пятниц на неделе.", "Семь пя́тниц на неде́ле.", "Sem pyatnits na nedele.", "He changes his mind constantly."],
        ["Как корова языком слизала.", "Как коро́ва языко́м слиза́ла.", "Kak korova yazykom slizala.", "Vanished without a trace."],
        ["Душа в пятки ушла.", "Душа́ в пя́тки ушла́.", "Dusha v pyatki ushla.", "My heart sank into my boots."],
        ["У него руки растут не из того места.", "У него́ ру́ки расту́т не из того́ ме́ста.", "U nego ruki rastut ne iz togo mesta.", "He has two left hands."],
        ["Он плывёт по течению.", "Он плывёт по тече́нию.", "On plyvyot po techeniyu.", "He goes with the flow."],
        ["Это седьмая вода на киселе.", "Э́то седьма́я вода́ на киселе́.", "Eto sedmaya voda na kisele.", "He's a distant relative."],
        ["Бить тревогу пора уже давно.", "Бить трево́гу пора́ уже́ давно́.", "Bit trevogu pora uzhe davno.", "It's high time to sound the alarm."],
        ["Я уже на нервах.", "Я уже́ на не́рвах.", "Ya uzhe na nervakh.", "I'm already on edge."],
        ["Хоть стой, хоть падай!", "Хоть стой, хоть па́дай!", "Khot stoy, khot paday!", "Unbelievable! (lit. either stand or fall)"],
        ["Это ни в какие ворота не лезет.", "Э́то ни в каки́е воро́та не ле́зет.", "Eto ni v kakie vorota ne lezet.", "It's beyond all bounds."],
        ["Ходить вокруг да около.", "Ходи́ть вокру́г да о́коло.", "Khodit vokrug da okolo.", "To beat around the bush."],
        ["Сидеть сложа руки.", "Сиде́ть сложа́ ру́ки.", "Sidet slozha ruki.", "To sit with folded hands (do nothing)."],
        ["Он встал не с той ноги.", "Он встал не с той ноги́.", "On vstal ne s toy nogi.", "He got out of bed on the wrong side."],
        ["У страха глаза велики.", "У стра́ха глаза́ велики́.", "U strakha glaza veliki.", "Fear has big eyes."],
        ["Голова идёт кругом.", "Голова́ идёт кру́гом.", "Golova idyot krugom.", "My head is spinning."],
        ["Уши вянут от такого разговора.", "У́ши вя́нут от тако́го разгово́ра.", "Ushi vyanut ot takogo razgovora.", "My ears wilt from such a conversation."],
        ["Это последняя капля!", "Э́то после́дняя ка́пля!", "Eto poslednyaya kaplya!", "That's the last straw!"],
        ["Между ними кошка пробежала.", "Ме́жду ни́ми ко́шка пробежа́ла.", "Mezhdu nimi koshka probezhala.", "Something has come between them."],
        ["Ну и дела!", "Ну и дела́!", "Nu i dela!", "Well, what a thing!"],
        ["Это просто отпад!", "Э́то про́сто отпа́д!", "Eto prosto otpad!", "It's just awesome!"],
        ["Класс! Я в восторге.", "Класс! Я в восто́рге.", "Klass! Ya v vostorge.", "Cool! I'm thrilled."],
        ["Не бери в голову.", "Не бери́ в го́лову.", "Ne beri v golovu.", "Don't take it to heart."],
        ["Ноги моей здесь больше не будет.", "Ноги́ мое́й здесь бо́льше не бу́дет.", "Nogi moey zdes bolshe ne budet.", "I'll never set foot here again."],
        ["Он спустил всё на тормозах.", "Он спусти́л всё на тормоза́х.", "On spustil vsyo na tormozakh.", "He let the matter drop quietly."],
        ["Глаз да глаз нужен за ним.", "Глаз да глаз ну́жен за ним.", "Glaz da glaz nuzhen za nim.", "He needs constant watching."],
        ["Вешать всех собак на кого-то.", "Ве́шать всех соба́к на кого́-то.", "Veshat vsekh sobak na kogo-to.", "To blame everything on someone."],
        ["У него язык без костей.", "У него́ язы́к без косте́й.", "U nego yazyk bez kostey.", "He talks too much."],
        ["Не сыпь мне соль на рану.", "Не сыпь мне соль на ра́ну.", "Ne syp mne sol na ranu.", "Don't rub salt in my wound."],
        ["Палец в рот не клади.", "Па́лец в рот не клади́.", "Palets v rot ne kladi.", "Don't put your finger in his mouth (he can stand up for himself)."],
        ["Ни рыба ни мясо.", "Ни ры́ба ни мя́со.", "Ni ryba ni myaso.", "Neither fish nor fowl."],
        ["Он крутится как белка в колесе.", "Он кру́тится как бе́лка в колесе́.", "On krutitsya kak belka v kolese.", "He's spinning like a squirrel in a wheel."],
        ["Голодный как волк.", "Голо́дный как волк.", "Golodnyy kak volk.", "Hungry as a wolf."],
        ["Делать что-то на скорую руку.", "Де́лать что́-то на ско́рую ру́ку.", "Delat chto-to na skoruyu ruku.", "To do something hastily."],
        ["Висит на волоске.", "Виси́т на волоске́.", "Visit na voloske.", "It hangs by a thread."],
        ["Кататься как сыр в масле.", "Ката́ться как сыр в ма́сле.", "Katatsya kak syr v masle.", "To live in clover (lit. roll like cheese in butter)."],
        ["В чужой монастырь со своим уставом не ходят.", "В чужо́й монасты́рь со свои́м уста́вом не хо́дят.", "V chuzhoy monastyr so svoim ustavom ne khodyat.", "When in Rome, do as the Romans do."],
        ["Что посеешь, то и пожнёшь.", "Что посе́ешь, то и пожнёшь.", "Chto poseesh, to i pozhnyosh.", "As you sow, so shall you reap."],
        ["Своя рубаха ближе к телу.", "Своя́ руба́ха бли́же к те́лу.", "Svoya rubakha blizhe k telu.", "Charity begins at home."],
        ["За двумя зайцами погонишься — ни одного не поймаешь.", "За двумя́ за́йцами пого́нишься — ни одного́ не пойма́ешь.", "Za dvumya zaytsami pogonishsya — ni odnogo ne poymaesh.", "If you chase two hares, you'll catch none."],
        ["Не плюй в колодец — пригодится воды напиться.", "Не плюй в коло́дец — пригоди́тся воды́ напи́ться.", "Ne plyuy v kolodets — prigoditsya vody napitsya.", "Don't spit in the well — you may need to drink from it."],
        ["Куй железо, пока горячо.", "Куй желе́зо, пока́ горячо́.", "Kuy zhelezo, poka goryacho.", "Strike while the iron is hot."],
    ],

    # ---------------- B2 Part 4: Literature, narrative, indirect speech ----------------
    "b2-part-4": [
        ["Он сказал, что приедет на следующей неделе.", "Он сказа́л, что прие́дет на сле́дующей неде́ле.", "On skazal, chto priedet na sleduyushchey nedele.", "He said he would come next week."],
        ["Она спросила, знаю ли я ответ.", "Она́ спроси́ла, зна́ю ли я отве́т.", "Ona sprosila, znayu li ya otvet.", "She asked whether I knew the answer."],
        ["Они объяснили, как добраться до музея.", "Они́ объясни́ли, как добра́ться до музе́я.", "Oni obyasnili, kak dobratsya do muzeya.", "They explained how to get to the museum."],
        ["Я не знал, что он давно уехал.", "Я не знал, что он давно́ уе́хал.", "Ya ne znal, chto on davno uekhal.", "I didn't know that he had left long ago."],
        ["Учитель попросил, чтобы все встали.", "Учи́тель попроси́л, что́бы все вста́ли.", "Uchitel poprosil, chtoby vse vstali.", "The teacher asked everyone to stand up."],
        ["Он рассказал, как провёл лето в деревне.", "Он рассказа́л, как провёл ле́то в дере́вне.", "On rasskazal, kak provyol leto v derevne.", "He told how he had spent the summer in the village."],
        ["Маша призналась, что давно мечтала о собаке.", "Ма́ша призна́лась, что давно́ мечта́ла о соба́ке.", "Masha priznalas, chto davno mechtala o sobake.", "Masha confessed that she had long dreamed of a dog."],
        ["Старик вздохнул и сказал: «Жизнь — странная штука».", "Стари́к вздохну́л и сказа́л: «Жизнь — стра́нная шту́ка».", "Starik vzdokhnul i skazal: «Zhizn — strannaya shtuka».", "The old man sighed and said: \"Life is a strange thing.\""],
        ["Главный герой романа — молодой офицер.", "Гла́вный геро́й рома́на — молодо́й офице́р.", "Glavnyy geroy romana — molodoy ofitser.", "The main character of the novel is a young officer."],
        ["Действие повести разворачивается в начале века.", "Де́йствие по́вести развора́чивается в нача́ле ве́ка.", "Deystvie povesti razvorachivaetsya v nachale veka.", "The action of the novella unfolds at the beginning of the century."],
        ["Автор тонко передаёт настроение своих героев.", "А́втор то́нко передаёт настрое́ние свои́х геро́ев.", "Avtor tonko peredayot nastroenie svoikh geroev.", "The author subtly conveys the mood of his characters."],
        ["В этом стихотворении звучит мотив одиночества.", "В э́том стихотворе́нии звучи́т моти́в одино́чества.", "V etom stikhotvorenii zvuchit motiv odinochestva.", "The motif of loneliness sounds in this poem."],
        ["Толстой исследует природу человеческой души.", "Толсто́й иссле́дует приро́ду челове́ческой души́.", "Tolstoy issleduet prirodu chelovecheskoy dushi.", "Tolstoy explores the nature of the human soul."],
        ["Произведение наполнено глубоким философским смыслом.", "Произведе́ние напо́лнено глубо́ким филосо́фским смы́слом.", "Proizvedenie napolneno glubokim filosofskim smyslom.", "The work is filled with deep philosophical meaning."],
        ["Сюжет романа держит читателя в напряжении до последней страницы.", "Сюже́т рома́на де́ржит чита́теля в напряже́нии до после́дней страни́цы.", "Syuzhet romana derzhit chitatelya v napryazhenii do posledney stranitsy.", "The novel's plot keeps the reader in suspense until the last page."],
        ["В этом рассказе мастерски использованы метафоры.", "В э́том расска́зе ма́стерски испо́льзованы мета́форы.", "V etom rasskaze masterski ispolzovany metafory.", "Metaphors are skillfully used in this story."],
        ["Образ матери в повести — символ безусловной любви.", "О́браз ма́тери в по́вести — си́мвол безусло́вной любви́.", "Obraz materi v povesti — simvol bezuslovnoy lyubvi.", "The image of the mother in the novella is a symbol of unconditional love."],
        ["Пушкин считается основоположником современной русской литературы.", "Пу́шкин счита́ется основополо́жником совреме́нной ру́сской литерату́ры.", "Pushkin schitaetsya osnovopolozhnikom sovremennoy russkoy literatury.", "Pushkin is considered the founder of modern Russian literature."],
        ["Чехов умел в нескольких строках раскрыть характер.", "Че́хов уме́л в не́скольких стро́ках раскры́ть хара́ктер.", "Chekhov umel v neskolkikh strokakh raskryt kharakter.", "Chekhov could reveal a character in just a few lines."],
        ["Достоевский поднимает вечные вопросы о добре и зле.", "Достое́вский поднима́ет ве́чные вопро́сы о добре́ и зле.", "Dostoevskiy podnimaet vechnye voprosy o dobre i zle.", "Dostoevsky raises eternal questions about good and evil."],
        ["Каждое слово в этом тексте имеет особое значение.", "Ка́ждое сло́во в э́том те́ксте име́ет осо́бое значе́ние.", "Kazhdoe slovo v etom tekste imeet osoboe znachenie.", "Every word in this text has a special meaning."],
        ["Повествование ведётся от первого лица.", "Повествова́ние ведётся от пе́рвого лица́.", "Povestvovanie vedyotsya ot pervogo litsa.", "The narration is conducted in the first person."],
        ["Финал произведения остаётся открытым.", "Фина́л произведе́ния остаётся откры́тым.", "Final proizvedeniya ostayotsya otkrytym.", "The ending of the work remains open."],
        ["Конфликт между героями разрешается неожиданно.", "Конфли́кт ме́жду геро́ями разреша́ется неожи́данно.", "Konflikt mezhdu geroyami razreshaetsya neozhidanno.", "The conflict between the heroes is resolved unexpectedly."],
        ["Книга оставляет глубокий след в душе.", "Кни́га оставля́ет глубо́кий след в душе́.", "Kniga ostavlyaet glubokiy sled v dushe.", "The book leaves a deep mark on the soul."],
        ["Однажды осенним вечером он постучал в нашу дверь.", "Одна́жды осе́нним ве́чером он постуча́л в на́шу дверь.", "Odnazhdy osennim vecherom on postuchal v nashu dver.", "One autumn evening he knocked at our door."],
        ["Никто не ожидал, что произойдёт такое.", "Никто́ не ожида́л, что произойдёт тако́е.", "Nikto ne ozhidal, chto proizoydyot takoe.", "Nobody expected that such a thing would happen."],
        ["С тех пор прошло много лет.", "С тех пор прошло́ мно́го лет.", "S tekh por proshlo mnogo let.", "Many years have passed since then."],
        ["Когда я вошёл в комнату, все замолчали.", "Когда́ я вошёл в ко́мнату, все замолча́ли.", "Kogda ya voshyol v komnatu, vse zamolchali.", "When I entered the room, everyone fell silent."],
        ["Не успел он сказать ни слова, как зазвонил телефон.", "Не успе́л он сказа́ть ни сло́ва, как зазвони́л телефо́н.", "Ne uspel on skazat ni slova, kak zazvonil telefon.", "He had hardly said a word when the phone rang."],
        ["Тишину нарушал лишь шум дождя за окном.", "Тишину́ наруша́л лишь шум дождя́ за окно́м.", "Tishinu narushal lish shum dozhdya za oknom.", "The silence was broken only by the sound of rain outside the window."],
        ["Луна освещала пустынную улицу.", "Луна́ освеща́ла пусты́нную у́лицу.", "Luna osveshchala pustynnuyu ulitsu.", "The moon lit the deserted street."],
        ["Он понял, что обратной дороги нет.", "Он по́нял, что обра́тной доро́ги нет.", "On ponyal, chto obratnoy dorogi net.", "He realized there was no way back."],
        ["В тот момент она почувствовала странное волнение.", "В тот моме́нт она́ почу́вствовала стра́нное волне́ние.", "V tot moment ona pochuvstvovala strannoe volnenie.", "At that moment she felt a strange agitation."],
        ["Его слова прозвучали как приговор.", "Его́ слова́ прозвуча́ли как пригово́р.", "Ego slova prozvuchali kak prigovor.", "His words sounded like a verdict."],
        ["Прошедший день оставил тяжёлое впечатление.", "Проше́дший день оста́вил тяжёлое впечатле́ние.", "Proshedshiy den ostavil tyazhyoloe vpechatlenie.", "The day that had passed left a heavy impression."],
        ["В её глазах блеснули слёзы.", "В её глаза́х блесну́ли слёзы.", "V eyo glazakh blesnuli slyozy.", "Tears glistened in her eyes."],
        ["Старый дом хранил воспоминания о прошлом.", "Ста́рый дом храни́л воспомина́ния о про́шлом.", "Staryy dom khranil vospominaniya o proshlom.", "The old house kept memories of the past."],
        ["Между ними возникла странная связь.", "Ме́жду ни́ми возни́кла стра́нная связь.", "Mezhdu nimi voznikla strannaya svyaz.", "A strange bond arose between them."],
        ["Судьба свела их вновь много лет спустя.", "Судьба́ свела́ их вновь мно́го лет спустя́.", "Sudba svela ikh vnov mnogo let spustya.", "Fate brought them together again many years later."],
        ["Он долго смотрел вдаль, не говоря ни слова.", "Он до́лго смотре́л вдаль, не говоря́ ни сло́ва.", "On dolgo smotrel vdal, ne govorya ni slova.", "He looked into the distance for a long time without saying a word."],
        ["Её рассказ напомнил мне о детстве.", "Её расска́з напо́мнил мне о де́тстве.", "Eyo rasskaz napomnil mne o detstve.", "Her story reminded me of childhood."],
        ["Странник присел у дороги и задумался.", "Стра́нник присе́л у доро́ги и заду́мался.", "Strannik prisel u dorogi i zadumalsya.", "The wanderer sat down by the road and pondered."],
        ["Деревья шептали что-то на ветру.", "Дере́вья шепта́ли что́-то на ветру́.", "Derevya sheptali chto-to na vetru.", "The trees whispered something in the wind."],
        ["Время будто остановилось в этот миг.", "Вре́мя бу́дто останови́лось в э́тот миг.", "Vremya budto ostanovilos v etot mig.", "Time seemed to stop at that moment."],
        ["Сердце забилось чаще от волнения.", "Се́рдце заби́лось ча́ще от волне́ния.", "Serdtse zabilos chashche ot volneniya.", "His heart beat faster from excitement."],
        ["Никто не мог понять, что произошло на самом деле.", "Никто́ не мог поня́ть, что произошло́ на са́мом де́ле.", "Nikto ne mog ponyat, chto proizoshlo na samom dele.", "No one could understand what had really happened."],
        ["Письмо пришло слишком поздно.", "Письмо́ пришло́ сли́шком по́здно.", "Pismo prishlo slishkom pozdno.", "The letter arrived too late."],
        ["Он вспоминал её улыбку всю жизнь.", "Он вспомина́л её улы́бку всю жизнь.", "On vspominal eyo ulybku vsyu zhizn.", "He remembered her smile all his life."],
        ["Каждое утро она приходила к этому окну.", "Ка́ждое у́тро она́ приходи́ла к э́тому окну́.", "Kazhdoe utro ona prikhodila k etomu oknu.", "Every morning she came to this window."],
        ["Их история закончилась грустно, но красиво.", "Их исто́рия зако́нчилась гру́стно, но краси́во.", "Ikh istoriya zakonchilas grustno, no krasivo.", "Their story ended sadly but beautifully."],
        ["Автор намекает на возможность счастливого финала.", "А́втор намека́ет на возмо́жность счастли́вого фина́ла.", "Avtor namekaet na vozmozhnost schastlivogo finala.", "The author hints at the possibility of a happy ending."],
        ["Сцена в саду — кульминация всего романа.", "Сце́на в саду́ — кульмина́ция всего́ рома́на.", "Stsena v sadu — kulminatsiya vsego romana.", "The garden scene is the climax of the entire novel."],
        ["Образы природы тесно переплетаются с чувствами героя.", "О́бразы приро́ды те́сно переплета́ются с чу́вствами геро́я.", "Obrazy prirody tesno perepletayutsya s chuvstvami geroya.", "Images of nature are closely intertwined with the hero's feelings."],
        ["Писатель противопоставляет добро и зло.", "Писа́тель противопоставля́ет добро́ и зло.", "Pisatel protivopostavlyaet dobro i zlo.", "The writer juxtaposes good and evil."],
        ["Этот рассказ написан в духе классической прозы.", "Э́тот расска́з напи́сан в ду́хе класси́ческой про́зы.", "Etot rasskaz napisan v dukhe klassicheskoy prozy.", "This story is written in the spirit of classical prose."],
        ["Лирический герой переживает глубокий внутренний конфликт.", "Лири́ческий геро́й пережива́ет глубо́кий вну́тренний конфли́кт.", "Liricheskiy geroy perezhivaet glubokiy vnutrenniy konflikt.", "The lyrical hero experiences a deep inner conflict."],
        ["Композиция произведения построена очень изящно.", "Компози́ция произведе́ния постро́ена о́чень изя́щно.", "Kompozitsiya proizvedeniya postroena ochen izyashchno.", "The composition of the work is built very elegantly."],
        ["Автор использует ретроспекцию для раскрытия характера.", "А́втор испо́льзует ретроспе́кцию для раскры́тия хара́ктера.", "Avtor ispolzuet retrospektsiyu dlya raskrytiya kharaktera.", "The author uses flashback to reveal character."],
        ["Многослойность сюжета поражает своей глубиной.", "Многосло́йность сюже́та поража́ет свое́й глубино́й.", "Mnogosloynost syuzheta porazhaet svoey glubinoy.", "The multilayered plot is striking in its depth."],
        ["Он спросил меня, давно ли я живу в Москве.", "Он спроси́л меня́, давно́ ли я живу́ в Москве́.", "On sprosil menya, davno li ya zhivu v Moskve.", "He asked me if I had lived in Moscow for a long time."],
        ["Она ответила, что не понимает, о чём идёт речь.", "Она́ отве́тила, что не понима́ет, о чём идёт речь.", "Ona otvetila, chto ne ponimaet, o chyom idyot rech.", "She replied that she didn't understand what was being said."],
        ["Друг предложил, чтобы мы встретились в субботу.", "Друг предложи́л, что́бы мы встре́тились в суббо́ту.", "Drug predlozhil, chtoby my vstretilis v subbotu.", "My friend suggested that we meet on Saturday."],
        ["Журналист поинтересовался, когда будет готов отчёт.", "Журнали́ст поинтересова́лся, когда́ бу́дет гото́в отчёт.", "Zhurnalist pointeresovalsya, kogda budet gotov otchyot.", "The journalist enquired when the report would be ready."],
        ["Все согласились, что план нуждается в доработке.", "Все согласи́лись, что план нужда́ется в дорабо́тке.", "Vse soglasilis, chto plan nuzhdaetsya v dorabotke.", "Everyone agreed that the plan needed refinement."],
        ["Я подумал, что было бы неплохо отдохнуть.", "Я поду́мал, что бы́ло бы непло́хо отдохну́ть.", "Ya podumal, chto bylo by neplokho otdokhnut.", "I thought it would be nice to rest."],
        ["Брат пообещал, что вернётся к ужину.", "Брат пообеща́л, что вернётся к у́жину.", "Brat poobeshchal, chto vernyotsya k uzhinu.", "My brother promised that he would return by dinner."],
        ["Сосед предупредил, чтобы мы не оставляли дверь открытой.", "Сосе́д предупреди́л, что́бы мы не оставля́ли дверь откры́той.", "Sosed predupredil, chtoby my ne ostavlyali dver otkrytoy.", "The neighbour warned us not to leave the door open."],
        ["Они потребовали, чтобы мы немедленно ушли.", "Они́ потре́бовали, что́бы мы неме́дленно ушли́.", "Oni potrebovali, chtoby my nemedlenno ushli.", "They demanded that we leave immediately."],
        ["Мать напомнила, что пора собираться в школу.", "Мать напо́мнила, что пора́ собира́ться в шко́лу.", "Mat napomnila, chto pora sobiratsya v shkolu.", "Mother reminded that it was time to get ready for school."],
        ["Девочка призналась, что ей было страшно одной.", "Де́вочка призна́лась, что ей бы́ло стра́шно одно́й.", "Devochka priznalas, chto ey bylo strashno odnoy.", "The girl confessed that she had been scared alone."],
        ["Учёный заявил, что результаты превзошли ожидания.", "Учёный заяви́л, что результа́ты превзошли́ ожида́ния.", "Uchyonyy zayavil, chto rezultaty prevzoshli ozhidaniya.", "The scientist stated that the results had exceeded expectations."],
        ["Свидетель уверял, что видел всё своими глазами.", "Свиде́тель уверя́л, что ви́дел всё свои́ми глаза́ми.", "Svidetel uveryal, chto videl vsyo svoimi glazami.", "The witness assured that he had seen everything with his own eyes."],
        ["Бабушка часто рассказывала, как трудно было в военные годы.", "Ба́бушка ча́сто расска́зывала, как тру́дно бы́ло в вое́нные го́ды.", "Babushka chasto rasskazyvala, kak trudno bylo v voennye gody.", "Grandmother often told how hard it had been during the war years."],
        ["Дед вспоминал, как ходил пешком в школу за десять километров.", "Дед вспомина́л, как ходи́л пешко́м в шко́лу за де́сять киломе́тров.", "Ded vspominal, kak khodil peshkom v shkolu za desyat kilometrov.", "Grandfather recalled how he had walked ten kilometres to school."],
        ["Профессор подчёркивал, что без труда нет успеха.", "Профе́ссор подчёркивал, что без труда́ нет успе́ха.", "Professor podchyorkival, chto bez truda net uspekha.", "The professor emphasized that without work there is no success."],
        ["Мне сказали, что собрание перенесли на завтра.", "Мне сказа́ли, что собра́ние перенесли́ на за́втра.", "Mne skazali, chto sobranie perenesli na zavtra.", "I was told the meeting was postponed to tomorrow."],
        ["Гид объяснил, как устроена эта старая крепость.", "Гид объясни́л, как устро́ена э́та ста́рая кре́пость.", "Gid obyasnil, kak ustroena eta staraya krepost.", "The guide explained how this old fortress was built."],
        ["Учитель отметил, что наша группа добилась прогресса.", "Учи́тель отме́тил, что на́ша гру́ппа доби́лась прогре́сса.", "Uchitel otmetil, chto nasha gruppa dobilas progressa.", "The teacher noted that our group had made progress."],
        ["Художник признался, что вдохновение приходит редко.", "Худо́жник призна́лся, что вдохнове́ние прихо́дит ре́дко.", "Khudozhnik priznalsya, chto vdokhnovenie prikhodit redko.", "The artist confessed that inspiration comes rarely."],
        ["Поэт писал так, словно говорил с самой жизнью.", "Поэ́т писа́л так, сло́вно говори́л с само́й жи́знью.", "Poet pisal tak, slovno govoril s samoy zhiznyu.", "The poet wrote as if he were speaking with life itself."],
        ["Книга, которую ты мне посоветовал, оказалась прекрасной.", "Кни́га, кото́рую ты мне посове́товал, оказа́лась прекра́сной.", "Kniga, kotoruyu ty mne posovetoval, okazalas prekrasnoy.", "The book you recommended to me turned out to be wonderful."],
        ["Тема одиночества проходит через всё творчество писателя.", "Те́ма одино́чества прохо́дит че́рез всё тво́рчество писа́теля.", "Tema odinochestva prokhodit cherez vsyo tvorchestvo pisatelya.", "The theme of loneliness runs through the writer's entire work."],
        ["В романе ярко показана эпоха перемен.", "В рома́не я́рко пока́зана эпо́ха переме́н.", "V romane yarko pokazana epokha peremen.", "The era of changes is vividly depicted in the novel."],
        ["Главная героиня — собирательный образ женщины своего времени.", "Гла́вная герои́ня — собира́тельный о́браз же́нщины своего́ вре́мени.", "Glavnaya geroinya — sobiratelnyy obraz zhenshchiny svoego vremeni.", "The main heroine is a collective image of a woman of her time."],
        ["Описание природы передаёт внутреннее состояние героя.", "Описа́ние приро́ды передаёт вну́треннее состоя́ние геро́я.", "Opisanie prirody peredayot vnutrennee sostoyanie geroya.", "The description of nature conveys the hero's inner state."],
        ["В каждом абзаце чувствуется тонкое наблюдение автора.", "В ка́ждом абза́це чу́вствуется то́нкое наблюде́ние а́втора.", "V kazhdom abzatse chuvstvuetsya tonkoe nablyudenie avtora.", "In every paragraph one feels the author's subtle observation."],
        ["Конфликт поколений — одна из главных тем произведения.", "Конфли́кт поколе́ний — одна́ из гла́вных тем произведе́ния.", "Konflikt pokoleniy — odna iz glavnykh tem proizvedeniya.", "The conflict of generations is one of the main themes of the work."],
        ["Финальная сцена оставляет читателя в раздумьях.", "Фина́льная сце́на оставля́ет чита́теля в разду́мьях.", "Finalnaya stsena ostavlyaet chitatelya v razdumyakh.", "The final scene leaves the reader in thought."],
        ["Автор не даёт готовых ответов, он лишь задаёт вопросы.", "А́втор не даёт гото́вых отве́тов, он лишь задаёт вопро́сы.", "Avtor ne dayot gotovykh otvetov, on lish zadayot voprosy.", "The author doesn't give ready answers, he only poses questions."],
        ["Этот текст стоит перечитать несколько раз.", "Э́тот текст сто́ит перечита́ть не́сколько раз.", "Etot tekst stoit perechitat neskolko raz.", "This text is worth rereading several times."],
        ["Каждое поколение находит в этой книге что-то своё.", "Ка́ждое поколе́ние нахо́дит в э́той кни́ге что́-то своё.", "Kazhdoe pokolenie nakhodit v etoy knige chto-to svoyo.", "Each generation finds something of its own in this book."],
        ["Время не властно над настоящими шедеврами.", "Вре́мя не вла́стно над настоя́щими шеде́врами.", "Vremya ne vlastno nad nastoyashchimi shedevrami.", "Time has no power over true masterpieces."],
        ["Литература помогает понять себя и других.", "Литерату́ра помога́ет поня́ть себя́ и други́х.", "Literatura pomogaet ponyat sebya i drugikh.", "Literature helps us understand ourselves and others."],
        ["Книги — это окно в мир человеческой души.", "Кни́ги — э́то окно́ в мир челове́ческой души́.", "Knigi — eto okno v mir chelovecheskoy dushi.", "Books are a window into the world of the human soul."],
        ["Хороший писатель видит то, что незаметно другим.", "Хоро́ший писа́тель ви́дит то, что незаме́тно други́м.", "Khoroshiy pisatel vidit to, chto nezametno drugim.", "A good writer sees what is unnoticed by others."],
        ["История повторяется, но каждый раз по-новому.", "Исто́рия повторя́ется, но ка́ждый раз по-но́вому.", "Istoriya povtoryaetsya, no kazhdyy raz po-novomu.", "History repeats itself, but each time in a new way."],
        ["Слова поэта живут дольше, чем сам поэт.", "Слова́ поэ́та живу́т до́льше, чем сам поэ́т.", "Slova poeta zhivut dolshe, chem sam poet.", "A poet's words live longer than the poet himself."],
        ["Истинное искусство не имеет границ.", "И́стинное иску́сство не име́ет грани́ц.", "Istinnoe iskusstvo ne imeet granits.", "True art has no borders."],
        ["Это произведение по праву считается шедевром мировой литературы.", "Э́то произведе́ние по пра́ву счита́ется шеде́вром мирово́й литерату́ры.", "Eto proizvedenie po pravu schitaetsya shedevrom mirovoy literatury.", "This work is rightfully considered a masterpiece of world literature."],
    ],
}

def write_part(key, rows):
    out = []
    for i, r in enumerate(rows, 1):
        out.append({
            "id": f"{key}-{i}",
            "ru": r[0],
            "ruStressed": r[1],
            "translit": r[2],
            "en": r[3],
        })
    path = os.path.join(OUT, f"{key}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"wrote {path}: {len(out)}")

for k, v in PARTS.items():
    write_part(k, v)
