#!/usr/bin/env python3
"""Generate A2 sentence JSON files. Each entry: [ru, ruStressed, translit, en]."""
import json, os

PARTS = {
    "a2-part-1": [
        # Daily routine & past tense — ~130 sentences
        ["Я обычно встаю в семь часов.", "Я обы́чно встаю́ в семь часо́в.", "Ya obychno vstayu v sem' chasov.", "I usually get up at seven."],
        ["Вчера я встал поздно.", "Вчера́ я встал по́здно.", "Vchera ya vstal pozdno.", "Yesterday I got up late."],
        ["Утром я пью кофе.", "У́тром я пью ко́фе.", "Utrom ya p'yu kofe.", "In the morning I drink coffee."],
        ["Я завтракаю дома.", "Я за́втракаю до́ма.", "Ya zavtrakayu doma.", "I have breakfast at home."],
        ["Вчера я завтракал в кафе.", "Вчера́ я за́втракал в кафе́.", "Vchera ya zavtrakal v kafe.", "Yesterday I had breakfast at a cafe."],
        ["Я принимаю душ каждое утро.", "Я принима́ю душ ка́ждое у́тро.", "Ya prinimayu dush kazhdoe utro.", "I take a shower every morning."],
        ["Я чищу зубы два раза в день.", "Я чи́щу зу́бы два ра́за в день.", "Ya chishchu zuby dva raza v den'.", "I brush my teeth twice a day."],
        ["Я одеваюсь быстро.", "Я одева́юсь бы́стро.", "Ya odevayus' bystro.", "I get dressed quickly."],
        ["Потом я иду на работу.", "Пото́м я иду́ на рабо́ту.", "Potom ya idu na rabotu.", "Then I go to work."],
        ["Я работаю с девяти до шести.", "Я рабо́таю с девяти́ до шести́.", "Ya rabotayu s devyati do shesti.", "I work from nine to six."],
        ["Вчера я работал весь день.", "Вчера́ я рабо́тал весь день.", "Vchera ya rabotal ves' den'.", "Yesterday I worked all day."],
        ["Я обедаю в столовой.", "Я обе́даю в столо́вой.", "Ya obedayu v stolovoy.", "I have lunch in the canteen."],
        ["В обед я ем суп.", "В обе́д я ем суп.", "V obed ya em sup.", "At lunch I eat soup."],
        ["После работы я иду домой.", "По́сле рабо́ты я иду́ домо́й.", "Posle raboty ya idu domoy.", "After work I go home."],
        ["Я ужинаю в восемь часов.", "Я у́жинаю в во́семь часо́в.", "Ya uzhinayu v vosem' chasov.", "I have dinner at eight."],
        ["Вечером я смотрю телевизор.", "Ве́чером я смотрю́ телеви́зор.", "Vecherom ya smotryu televizor.", "In the evening I watch TV."],
        ["Я читаю книгу перед сном.", "Я чита́ю кни́гу пе́ред сном.", "Ya chitayu knigu pered snom.", "I read a book before bed."],
        ["Я ложусь спать в одиннадцать.", "Я ложу́сь спать в оди́ннадцать.", "Ya lozhus' spat' v odinnadtsat'.", "I go to bed at eleven."],
        ["Вчера я лёг спать поздно.", "Вчера́ я лёг спать по́здно.", "Vchera ya lyog spat' pozdno.", "Yesterday I went to bed late."],
        ["Я сплю восемь часов.", "Я сплю во́семь часо́в.", "Ya splyu vosem' chasov.", "I sleep eight hours."],
        ["В выходные я отдыхаю.", "В выходны́е я отдыха́ю.", "V vykhodnye ya otdykhayu.", "On weekends I rest."],
        ["В субботу я хожу в спортзал.", "В суббо́ту я хожу́ в спортза́л.", "V subbotu ya khozhu v sportzal.", "On Saturday I go to the gym."],
        ["В воскресенье я гуляю в парке.", "В воскресе́нье я гуля́ю в па́рке.", "V voskresen'e ya gulyayu v parke.", "On Sunday I walk in the park."],
        ["Вчера я гулял с друзьями.", "Вчера́ я гуля́л с друзья́ми.", "Vchera ya gulyal s druz'yami.", "Yesterday I walked with friends."],
        ["Я часто хожу в кино.", "Я ча́сто хожу́ в кино́.", "Ya chasto khozhu v kino.", "I often go to the cinema."],
        ["На прошлой неделе я был в театре.", "На про́шлой неде́ле я был в теа́тре.", "Na proshloy nedele ya byl v teatre.", "Last week I was at the theater."],
        ["Я редко смотрю спорт.", "Я ре́дко смотрю́ спорт.", "Ya redko smotryu sport.", "I rarely watch sports."],
        ["Иногда я готовлю ужин.", "Иногда́ я гото́влю у́жин.", "Inogda ya gotovlyu uzhin.", "Sometimes I cook dinner."],
        ["Вчера я приготовил пасту.", "Вчера́ я пригото́вил па́сту.", "Vchera ya prigotovil pastu.", "Yesterday I cooked pasta."],
        ["Я мою посуду после ужина.", "Я мо́ю посу́ду по́сле у́жина.", "Ya moyu posudu posle uzhina.", "I wash the dishes after dinner."],
        ["Я убираю квартиру по субботам.", "Я убира́ю кварти́ру по суббо́там.", "Ya ubirayu kvartiru po subbotam.", "I clean the apartment on Saturdays."],
        ["Вчера я убрал свою комнату.", "Вчера́ я убра́л свою́ ко́мнату.", "Vchera ya ubral svoyu komnatu.", "Yesterday I cleaned my room."],
        ["Я стираю одежду раз в неделю.", "Я стира́ю оде́жду раз в неде́лю.", "Ya stirayu odezhdu raz v nedelyu.", "I do laundry once a week."],
        ["Я хожу в магазин по дороге домой.", "Я хожу́ в магази́н по доро́ге домо́й.", "Ya khozhu v magazin po doroge domoy.", "I go to the store on the way home."],
        ["Вчера я купил хлеб и молоко.", "Вчера́ я купи́л хлеб и молоко́.", "Vchera ya kupil khleb i moloko.", "Yesterday I bought bread and milk."],
        ["Я езжу на работу на метро.", "Я е́зжу на рабо́ту на метро́.", "Ya ezzhu na rabotu na metro.", "I commute to work by metro."],
        ["Вчера я ехал на автобусе.", "Вчера́ я е́хал на авто́бусе.", "Vchera ya yekhal na avtobuse.", "Yesterday I rode the bus."],
        ["Дорога занимает полчаса.", "Доро́га занима́ет полчаса́.", "Doroga zanimaet polchasa.", "The trip takes half an hour."],
        ["Я слушаю музыку в дороге.", "Я слу́шаю му́зыку в доро́ге.", "Ya slushayu muzyku v doroge.", "I listen to music on the way."],
        ["Я начинаю день с зарядки.", "Я начина́ю день с заря́дки.", "Ya nachinayu den' s zaryadki.", "I start the day with exercise."],
        ["Я заканчиваю работу в шесть.", "Я зака́нчиваю рабо́ту в шесть.", "Ya zakanchivayu rabotu v shest'.", "I finish work at six."],
        ["Вчера я закончил рано.", "Вчера́ я зако́нчил ра́но.", "Vchera ya zakonchil rano.", "Yesterday I finished early."],
        ["Я звоню маме каждый день.", "Я звоню́ ма́ме ка́ждый день.", "Ya zvonyu mame kazhdyy den'.", "I call my mom every day."],
        ["Вчера я звонил брату.", "Вчера́ я звони́л бра́ту.", "Vchera ya zvonil bratu.", "Yesterday I called my brother."],
        ["Мы разговаривали час.", "Мы разгова́ривали час.", "My razgovarivali chas.", "We talked for an hour."],
        ["Я пишу письма редко.", "Я пишу́ пи́сьма ре́дко.", "Ya pishu pis'ma redko.", "I rarely write letters."],
        ["Вчера я написал ей сообщение.", "Вчера́ я написа́л ей сообще́ние.", "Vchera ya napisal yey soobshchenie.", "Yesterday I wrote her a message."],
        ["Я учу русский язык.", "Я учу́ ру́сский язы́к.", "Ya uchu russkiy yazyk.", "I'm learning Russian."],
        ["Вчера я выучил десять слов.", "Вчера́ я вы́учил де́сять слов.", "Vchera ya vyuchil desyat' slov.", "Yesterday I learned ten words."],
        ["Я занимаюсь по часу в день.", "Я занима́юсь по ча́су в день.", "Ya zanimayus' po chasu v den'.", "I study one hour a day."],
        ["Сегодня я устал.", "Сего́дня я уста́л.", "Segodnya ya ustal.", "Today I'm tired."],
        ["Вчера было много работы.", "Вчера́ бы́ло мно́го рабо́ты.", "Vchera bylo mnogo raboty.", "Yesterday there was a lot of work."],
        ["Я не люблю вставать рано.", "Я не люблю́ встава́ть ра́но.", "Ya ne lyublyu vstavat' rano.", "I don't like getting up early."],
        ["Сегодня я проспал.", "Сего́дня я проспа́л.", "Segodnya ya prospal.", "Today I overslept."],
        ["Обычно я опаздываю редко.", "Обы́чно я опа́здываю ре́дко.", "Obychno ya opazdyvayu redko.", "I'm usually rarely late."],
        ["Вчера я опоздал на встречу.", "Вчера́ я опозда́л на встре́чу.", "Vchera ya opozdal na vstrechu.", "Yesterday I was late for a meeting."],
        ["Я встретил старого друга.", "Я встре́тил ста́рого дру́га.", "Ya vstretil starogo druga.", "I met an old friend."],
        ["Мы пили кофе вместе.", "Мы пи́ли ко́фе вме́сте.", "My pili kofe vmeste.", "We drank coffee together."],
        ["Я люблю утренний кофе.", "Я люблю́ у́тренний ко́фе.", "Ya lyublyu utrenniy kofe.", "I love morning coffee."],
        ["Каждый день одно и то же.", "Ка́ждый день одно́ и то же.", "Kazhdyy den' odno i to zhe.", "Every day is the same."],
        ["Сегодня я хочу отдохнуть.", "Сего́дня я хочу́ отдохну́ть.", "Segodnya ya khochu otdokhnut'.", "Today I want to rest."],
        ["Я уже позавтракал.", "Я уже́ поза́втракал.", "Ya uzhe pozavtrakal.", "I've already had breakfast."],
        ["Я ещё не обедал.", "Я ещё не обе́дал.", "Ya yeshchyo ne obedal.", "I haven't had lunch yet."],
        ["Утром я бегал в парке.", "У́тром я бе́гал в па́рке.", "Utrom ya begal v parke.", "In the morning I ran in the park."],
        ["Я часто бегаю по утрам.", "Я ча́сто бе́гаю по утра́м.", "Ya chasto begayu po utram.", "I often run in the mornings."],
        ["Раньше я курил, но бросил.", "Ра́ньше я кури́л, но бро́сил.", "Ran'she ya kuril, no brosil.", "I used to smoke, but I quit."],
        ["Раньше я жил в Москве.", "Ра́ньше я жил в Москве́.", "Ran'she ya zhil v Moskve.", "I used to live in Moscow."],
        ["В детстве я играл в футбол.", "В де́тстве я игра́л в футбо́л.", "V detstve ya igral v futbol.", "As a child I played football."],
        ["Я родился в маленьком городе.", "Я роди́лся в ма́леньком го́роде.", "Ya rodilsya v malen'kom gorode.", "I was born in a small city."],
        ["Я учился в школе двенадцать лет.", "Я учи́лся в шко́ле двена́дцать лет.", "Ya uchilsya v shkole dvenadtsat' let.", "I went to school for twelve years."],
        ["Потом я поступил в университет.", "Пото́м я поступи́л в университе́т.", "Potom ya poступи́л v universitet.", "Then I entered university."],
        ["Я окончил университет в прошлом году.", "Я око́нчил университе́т в про́шлом году́.", "Ya okonchil universitet v proshlom godu.", "I graduated university last year."],
        ["Сейчас я работаю инженером.", "Сейча́с я рабо́таю инжене́ром.", "Seychas ya rabotayu inzhenerom.", "Now I work as an engineer."],
        ["Я работаю здесь два года.", "Я рабо́таю здесь два го́да.", "Ya rabotayu zdes' dva goda.", "I've been working here for two years."],
        ["Я живу один.", "Я живу́ оди́н.", "Ya zhivu odin.", "I live alone."],
        ["Раньше я жил с родителями.", "Ра́ньше я жил с роди́телями.", "Ran'she ya zhil s roditelyami.", "I used to live with my parents."],
        ["Я переехал в новую квартиру.", "Я перее́хал в но́вую кварти́ру.", "Ya pereekhal v novuyu kvartiru.", "I moved to a new apartment."],
        ["Квартира маленькая, но уютная.", "Кварти́ра ма́ленькая, но ую́тная.", "Kvartira malen'kaya, no uyutnaya.", "The apartment is small but cozy."],
        ["В моей комнате есть стол и кровать.", "В мое́й ко́мнате есть стол и крова́ть.", "V moey komnate yest' stol i krovat'.", "In my room there's a table and a bed."],
        ["Я завтракал быстро сегодня.", "Я за́втракал бы́стро сего́дня.", "Ya zavtrakal bystro segodnya.", "I had breakfast quickly today."],
        ["Вчера весь день шёл дождь.", "Вчера́ весь день шёл дождь.", "Vchera ves' den' shyol dozhd'.", "Yesterday it rained all day."],
        ["Я сидел дома и читал.", "Я сиде́л до́ма и чита́л.", "Ya sidel doma i chital.", "I sat at home and read."],
        ["Книга была очень интересная.", "Кни́га была́ о́чень интере́сная.", "Kniga byla ochen' interesnaya.", "The book was very interesting."],
        ["Я прочитал её за два дня.", "Я прочита́л её за два дня.", "Ya prochital yeyo za dva dnya.", "I read it in two days."],
        ["Вчера я смотрел новый фильм.", "Вчера́ я смотре́л но́вый фильм.", "Vchera ya smotrel novyy fil'm.", "Yesterday I watched a new film."],
        ["Фильм мне понравился.", "Фильм мне понра́вился.", "Fil'm mne ponravilsya.", "I liked the film."],
        ["Я лёг спать после полуночи.", "Я лёг спать по́сле полу́ночи.", "Ya lyog spat' posle polunochi.", "I went to sleep after midnight."],
        ["Утром я проснулся уставшим.", "У́тром я просну́лся уста́вшим.", "Utrom ya prosnulsya ustavshim.", "In the morning I woke up tired."],
        ["Я выпил две чашки кофе.", "Я вы́пил две ча́шки ко́фе.", "Ya vypil dve chashki kofe.", "I drank two cups of coffee."],
        ["Кофе помог мне проснуться.", "Ко́фе помо́г мне просну́ться.", "Kofe pomog mne prosnut'sya.", "The coffee helped me wake up."],
        ["Сегодня день начался плохо.", "Сего́дня день начался́ пло́хо.", "Segodnya den' nachalsya plokho.", "Today started badly."],
        ["Но потом всё стало лучше.", "Но пото́м всё ста́ло лу́чше.", "No potom vsyo stalo luchshe.", "But then everything got better."],
        ["Я люблю спокойные вечера.", "Я люблю́ споко́йные вечера́.", "Ya lyublyu spokoynye vechera.", "I love quiet evenings."],
        ["Сегодня я никуда не пойду.", "Сего́дня я никуда́ не пойду́.", "Segodnya ya nikuda ne poydu.", "Today I'm not going anywhere."],
        ["Я хочу выспаться.", "Я хочу́ вы́спаться.", "Ya khochu vyspat'sya.", "I want to get enough sleep."],
        ["Завтра трудный день.", "За́втра тру́дный день.", "Zavtra trudnyy den'.", "Tomorrow is a hard day."],
        ["Я подготовился к встрече.", "Я подгото́вился к встре́че.", "Ya podgotovilsya k vstreche.", "I prepared for the meeting."],
        ["Я проверил почту.", "Я прове́рил по́чту.", "Ya proveril pochtu.", "I checked the mail."],
        ["Пришло пять новых писем.", "Пришло́ пять но́вых пи́сем.", "Prishlo pyat' novykh pisem.", "Five new emails came."],
        ["Я ответил на все письма.", "Я отве́тил на все пи́сьма.", "Ya otvetil na vse pis'ma.", "I replied to all the emails."],
        ["Потом я сделал чай.", "Пото́м я сде́лал чай.", "Potom ya sdelal chay.", "Then I made tea."],
        ["Я пью чай без сахара.", "Я пью чай без са́хара.", "Ya p'yu chay bez sakhara.", "I drink tea without sugar."],
        ["Утром был сильный туман.", "У́тром был си́льный тума́н.", "Utrom byl sil'nyy tuman.", "There was thick fog in the morning."],
        ["Я долго ждал автобус.", "Я до́лго ждал авто́бус.", "Ya dolgo zhdal avtobus.", "I waited for the bus for a long time."],
        ["Автобус опоздал на десять минут.", "Авто́бус опозда́л на де́сять мину́т.", "Avtobus opozdal na desyat' minut.", "The bus was ten minutes late."],
        ["Я приехал на работу вовремя.", "Я прие́хал на рабо́ту во́время.", "Ya priekhal na rabotu vovremya.", "I got to work on time."],
        ["На обед я ел салат.", "На обе́д я ел сала́т.", "Na obed ya yel salat.", "For lunch I ate a salad."],
        ["Салат был свежий и вкусный.", "Сала́т был све́жий и вку́сный.", "Salat byl svezhiy i vkusnyy.", "The salad was fresh and tasty."],
        ["После обеда я пил кофе.", "По́сле обе́да я пил ко́фе.", "Posle obeda ya pil kofe.", "After lunch I drank coffee."],
        ["Я работал до позднего вечера.", "Я рабо́тал до по́зднего ве́чера.", "Ya rabotal do pózdnego vechera.", "I worked until late evening."],
        ["Дома меня ждал ужин.", "До́ма меня́ ждал у́жин.", "Doma menya zhdal uzhin.", "Dinner was waiting for me at home."],
        ["Я был очень голодный.", "Я был о́чень голо́дный.", "Ya byl ochen' golodnyy.", "I was very hungry."],
        ["После ужина я смотрел сериал.", "По́сле у́жина я смотре́л сериа́л.", "Posle uzhina ya smotrel serial.", "After dinner I watched a series."],
        ["Я посмотрел три серии.", "Я посмотре́л три се́рии.", "Ya posmotrel tri serii.", "I watched three episodes."],
        ["Потом я почитал немного.", "Пото́м я почита́л немно́го.", "Potom ya pochital nemnogo.", "Then I read a little."],
        ["И лёг спать.", "И лёг спать.", "I lyog spat'.", "And went to bed."],
        ["Эта неделя была долгой.", "Э́та неде́ля была́ до́лгой.", "Eta nedelya byla dolgoy.", "This week was long."],
        ["Я жду выходных.", "Я жду выходны́х.", "Ya zhdu vykhodnykh.", "I'm waiting for the weekend."],
        ["В субботу я пойду на концерт.", "В суббо́ту я пойду́ на конце́рт.", "V subbotu ya poydu na kontsert.", "On Saturday I'll go to a concert."],
        ["В воскресенье я буду спать долго.", "В воскресе́нье я бу́ду спать до́лго.", "V voskresen'e ya budu spat' dolgo.", "On Sunday I'll sleep in."],
        ["Я люблю свободное время.", "Я люблю́ свобо́дное вре́мя.", "Ya lyublyu svobodnoe vremya.", "I love free time."],
        ["В свободное время я рисую.", "В свобо́дное вре́мя я рису́ю.", "V svobodnoe vremya ya risuyu.", "In my free time I draw."],
        ["Раньше я играл на гитаре.", "Ра́ньше я игра́л на гита́ре.", "Ran'she ya igral na gitare.", "I used to play guitar."],
        ["Сейчас у меня нет времени.", "Сейча́с у меня́ нет вре́мени.", "Seychas u menya net vremeni.", "Now I don't have time."],
        ["Дни летят очень быстро.", "Дни летя́т о́чень бы́стро.", "Dni letyat ochen' bystro.", "The days fly very fast."],
        ["Год прошёл незаметно.", "Год прошёл незаме́тно.", "God proshyol nezametno.", "The year passed unnoticed."],
        ["Прошлым летом я был в Италии.", "Про́шлым ле́том я был в Ита́лии.", "Proshlym letom ya byl v Italii.", "Last summer I was in Italy."],
        ["Это было незабываемо.", "Э́то бы́ло незабыва́емо.", "Eto bylo nezabyvaemo.", "It was unforgettable."],
        ["Я хочу поехать туда снова.", "Я хочу́ пое́хать туда́ сно́ва.", "Ya khochu poekhat' tuda snova.", "I want to go there again."],
        ["Сегодня я почувствовал себя лучше.", "Сего́дня я почу́вствовал себя́ лу́чше.", "Segodnya ya pochuvstvoval sebya luchshe.", "Today I felt better."],
        ["Вчера у меня болела голова.", "Вчера́ у меня́ боле́ла голова́.", "Vchera u menya bolela golova.", "Yesterday I had a headache."],
        ["Я выпил таблетку и лёг.", "Я вы́пил табле́тку и лёг.", "Ya vypil tabletku i lyog.", "I took a pill and lay down."],
        ["Я проспал почти двенадцать часов.", "Я проспа́л почти́ двена́дцать часо́в.", "Ya prospal pochti dvenadtsat' chasov.", "I slept almost twelve hours."],
        ["Утром я был как новый.", "У́тром я был как но́вый.", "Utrom ya byl kak novyy.", "In the morning I felt like new."],
    ],
    "a2-part-2": [
        # Food, ordering, modal verbs
        ["Я хочу есть.", "Я хочу́ есть.", "Ya khochu yest'.", "I want to eat."],
        ["Я очень голоден.", "Я о́чень го́лоден.", "Ya ochen' goloden.", "I'm very hungry."],
        ["Что вы хотите заказать?", "Что вы хоти́те заказа́ть?", "Chto vy khotite zakazat'?", "What would you like to order?"],
        ["Можно меню, пожалуйста?", "Мо́жно меню́, пожа́луйста?", "Mozhno menyu, pozhaluysta?", "May I have the menu, please?"],
        ["Что вы порекомендуете?", "Что вы порекоменду́ете?", "Chto vy porekomenduete?", "What do you recommend?"],
        ["Я возьму суп и салат.", "Я возьму́ суп и сала́т.", "Ya voz'mu sup i salat.", "I'll have soup and salad."],
        ["Что есть на завтрак?", "Что есть на за́втрак?", "Chto yest' na zavtrak?", "What's for breakfast?"],
        ["На завтрак есть омлет и каша.", "На за́втрак есть омле́т и ка́ша.", "Na zavtrak yest' omlet i kasha.", "There's omelette and porridge for breakfast."],
        ["Мне, пожалуйста, чёрный кофе.", "Мне, пожа́луйста, чёрный ко́фе.", "Mne, pozhaluysta, chyornyy kofe.", "Black coffee for me, please."],
        ["С сахаром или без?", "С са́харом и́ли без?", "S sakharom ili bez?", "With sugar or without?"],
        ["Без сахара, спасибо.", "Без са́хара, спаси́бо.", "Bez sakhara, spasibo.", "Without sugar, thanks."],
        ["Я люблю чай с лимоном.", "Я люблю́ чай с лимо́ном.", "Ya lyublyu chay s limonom.", "I like tea with lemon."],
        ["Можно ещё воды?", "Мо́жно ещё воды́?", "Mozhno yeshchyo vody?", "May I have more water?"],
        ["Воду с газом или без?", "Во́ду с га́зом и́ли без?", "Vodu s gazom ili bez?", "Sparkling or still water?"],
        ["Без газа, пожалуйста.", "Без га́за, пожа́луйста.", "Bez gaza, pozhaluysta.", "Still, please."],
        ["Я не ем мясо.", "Я не ем мя́со.", "Ya ne yem myaso.", "I don't eat meat."],
        ["Я вегетарианец.", "Я вегетариа́нец.", "Ya vegetarianets.", "I'm a vegetarian."],
        ["У вас есть вегетарианские блюда?", "У вас есть вегетариа́нские блю́да?", "U vas yest' vegetarianskie blyuda?", "Do you have vegetarian dishes?"],
        ["Я не ем рыбу.", "Я не ем ры́бу.", "Ya ne yem rybu.", "I don't eat fish."],
        ["У меня аллергия на орехи.", "У меня́ аллерги́я на оре́хи.", "U menya allergiya na orekhi.", "I'm allergic to nuts."],
        ["Это блюдо острое?", "Э́то блю́до о́строе?", "Eto blyudo ostroe?", "Is this dish spicy?"],
        ["Я не люблю острое.", "Я не люблю́ о́строе.", "Ya ne lyublyu ostroe.", "I don't like spicy food."],
        ["Это очень вкусно!", "Э́то о́чень вку́сно!", "Eto ochen' vkusno!", "This is very tasty!"],
        ["Мне нравится эта еда.", "Мне нра́вится э́та еда́.", "Mne nravitsya eta yeda.", "I like this food."],
        ["Можно счёт, пожалуйста?", "Мо́жно счёт, пожа́луйста?", "Mozhno schyot, pozhaluysta?", "Could I have the bill, please?"],
        ["Я могу заплатить картой?", "Я могу́ заплати́ть ка́ртой?", "Ya mogu zaplatit' kartoy?", "Can I pay by card?"],
        ["Конечно, можно картой.", "Коне́чно, мо́жно ка́ртой.", "Konechno, mozhno kartoy.", "Of course, you can pay by card."],
        ["Сколько с меня?", "Ско́лько с меня́?", "Skol'ko s menya?", "How much do I owe?"],
        ["С вас пятьсот рублей.", "С вас пятьсо́т рубле́й.", "S vas pyatsot rubley.", "That'll be five hundred rubles."],
        ["Сдачу оставьте себе.", "Сда́чу оста́вьте себе́.", "Sdachu ostav'te sebe.", "Keep the change."],
        ["Спасибо, всё было отлично.", "Спаси́бо, всё бы́ло отли́чно.", "Spasibo, vsyo bylo otlichno.", "Thanks, everything was great."],
        ["Можно мне ещё хлеба?", "Мо́жно мне ещё хле́ба?", "Mozhno mne yeshchyo khleba?", "Can I have more bread?"],
        ["Передайте мне соль, пожалуйста.", "Переда́йте мне соль, пожа́луйста.", "Peredayte mne sol', pozhaluysta.", "Pass me the salt, please."],
        ["Это слишком солёное.", "Э́то сли́шком солёное.", "Eto slishkom solyonoe.", "This is too salty."],
        ["Можно сделать менее сладко?", "Мо́жно сде́лать ме́нее сла́дко?", "Mozhno sdelat' menee sladko?", "Could you make it less sweet?"],
        ["Я хочу что-нибудь горячее.", "Я хочу́ что-нибу́дь горя́чее.", "Ya khochu chto-nibud' goryachee.", "I want something hot."],
        ["А на десерт что есть?", "А на десе́рт что есть?", "A na desert chto yest'?", "And for dessert, what is there?"],
        ["У нас есть торт и мороженое.", "У нас есть торт и моро́женое.", "U nas yest' tort i morozhenoe.", "We have cake and ice cream."],
        ["Мне мороженое, пожалуйста.", "Мне моро́женое, пожа́луйста.", "Mne morozhenoe, pozhaluysta.", "Ice cream for me, please."],
        ["Какие фрукты у вас есть?", "Каки́е фру́кты у вас есть?", "Kakie frukty u vas yest'?", "What fruits do you have?"],
        ["У нас есть яблоки и груши.", "У нас есть я́блоки и гру́ши.", "U nas yest' yabloki i grushi.", "We have apples and pears."],
        ["Дайте мне килограмм яблок.", "Да́йте мне килогра́мм я́блок.", "Dayte mne kilogramm yablok.", "Give me a kilogram of apples."],
        ["Сколько стоит этот сыр?", "Ско́лько сто́ит э́тот сыр?", "Skol'ko stoit etot syr?", "How much is this cheese?"],
        ["Двести рублей за сто грамм.", "Две́сти рубле́й за сто грамм.", "Dvesti rubley za sto gramm.", "Two hundred rubles per hundred grams."],
        ["Это дорого.", "Э́то до́рого.", "Eto dorogo.", "That's expensive."],
        ["А есть что-нибудь подешевле?", "А есть что-нибу́дь подеше́вле?", "A yest' chto-nibud' podeshevle?", "Is there something cheaper?"],
        ["Я хочу купить хлеб.", "Я хочу́ купи́ть хлеб.", "Ya khochu kupit' khleb.", "I want to buy bread."],
        ["Где можно купить молоко?", "Где мо́жно купи́ть молоко́?", "Gde mozhno kupit' moloko?", "Where can I buy milk?"],
        ["Молоко вон там, в холодильнике.", "Молоко́ вон там, в холоди́льнике.", "Moloko von tam, v kholodil'nike.", "Milk is over there, in the fridge."],
        ["Я не умею готовить.", "Я не уме́ю гото́вить.", "Ya ne umeyu gotovit'.", "I can't cook."],
        ["Моя мама умеет готовить отлично.", "Моя́ ма́ма уме́ет гото́вить отли́чно.", "Moya mama umeet gotovit' otlichno.", "My mom cooks great."],
        ["Я могу приготовить пасту.", "Я могу́ пригото́вить па́сту.", "Ya mogu prigotovit' pastu.", "I can make pasta."],
        ["Ты должен попробовать борщ.", "Ты до́лжен попро́бовать борщ.", "Ty dolzhen poprobovat' borshch.", "You must try borscht."],
        ["Я никогда не пробовал суши.", "Я никогда́ не про́бовал су́ши.", "Ya nikogda ne proboval sushi.", "I've never tried sushi."],
        ["Хочешь попробовать?", "Хо́чешь попро́бовать?", "Khochesh' poprobovat'?", "Want to try it?"],
        ["Да, с удовольствием.", "Да, с удово́льствием.", "Da, s udovol'stviem.", "Yes, with pleasure."],
        ["Нет, спасибо, я сыт.", "Нет, спаси́бо, я сыт.", "Net, spasibo, ya syt.", "No thanks, I'm full."],
        ["Приятного аппетита!", "Прия́тного аппети́та!", "Priyatnogo appetita!", "Enjoy your meal!"],
        ["Это мой любимый ресторан.", "Э́то мой люби́мый рестора́н.", "Eto moy lyubimyy restoran.", "This is my favorite restaurant."],
        ["Здесь всегда вкусно.", "Здесь всегда́ вку́сно.", "Zdes' vsegda vkusno.", "It's always tasty here."],
        ["Закажем пиццу?", "Зака́жем пи́ццу?", "Zakazhem pittsu?", "Shall we order pizza?"],
        ["Какую пиццу ты хочешь?", "Каку́ю пи́ццу ты хо́чешь?", "Kakuyu pittsu ty khochesh'?", "What pizza do you want?"],
        ["Я хочу с грибами и сыром.", "Я хочу́ с гриба́ми и сы́ром.", "Ya khochu s gribami i syrom.", "I want one with mushrooms and cheese."],
        ["Можно мне без лука?", "Мо́жно мне без лу́ка?", "Mozhno mne bez luka?", "Could I have it without onion?"],
        ["Я не люблю лук.", "Я не люблю́ лук.", "Ya ne lyublyu luk.", "I don't like onion."],
        ["Принесите воду без льда.", "Принеси́те во́ду без льда.", "Prinesite vodu bez l'da.", "Bring water without ice."],
        ["Можно столик у окна?", "Мо́жно сто́лик у окна́?", "Mozhno stolik u okna?", "Could we have a table by the window?"],
        ["У вас есть столик на двоих?", "У вас есть сто́лик на двои́х?", "U vas yest' stolik na dvoikh?", "Do you have a table for two?"],
        ["Я заказал столик на восемь.", "Я заказа́л сто́лик на во́семь.", "Ya zakazal stolik na vosem'.", "I reserved a table for eight."],
        ["На какое имя?", "На како́е и́мя?", "Na kakoe imya?", "Under what name?"],
        ["На имя Иванов.", "На и́мя Ивано́в.", "Na imya Ivanov.", "Under Ivanov."],
        ["Принесите мне ещё одну вилку.", "Принеси́те мне ещё одну́ ви́лку.", "Prinesite mne yeshchyo odnu vilku.", "Bring me another fork."],
        ["У меня нет ножа.", "У меня́ нет ножа́.", "U menya net nozha.", "I don't have a knife."],
        ["Это не моё блюдо.", "Э́то не моё блю́до.", "Eto ne moyo blyudo.", "This isn't my dish."],
        ["Я заказывал курицу, а не рыбу.", "Я зака́зывал ку́рицу, а не ры́бу.", "Ya zakazyval kuritsu, a ne rybu.", "I ordered chicken, not fish."],
        ["Извините за ошибку.", "Извини́те за оши́бку.", "Izvinite za oshibku.", "Sorry for the mistake."],
        ["Сейчас принесу правильное.", "Сейча́с принесу́ пра́вильное.", "Seychas prinesu pravil'noe.", "I'll bring the correct one now."],
        ["Это блюдо холодное.", "Э́то блю́до холо́дное.", "Eto blyudo kholodnoe.", "This dish is cold."],
        ["Можно подогреть?", "Мо́жно подогре́ть?", "Mozhno podogret'?", "Could you reheat it?"],
        ["Я могу взять остатки с собой?", "Я могу́ взять оста́тки с собо́й?", "Ya mogu vzyat' ostatki s soboy?", "Can I take the leftovers with me?"],
        ["Конечно, я упакую.", "Коне́чно, я упаку́ю.", "Konechno, ya upakuyu.", "Of course, I'll pack it up."],
        ["Кафе закрывается в десять.", "Кафе́ закрыва́ется в де́сять.", "Kafe zakryvaetsya v desyat'.", "The cafe closes at ten."],
        ["Когда вы открываетесь?", "Когда́ вы открыва́етесь?", "Kogda vy otkryvaetes'?", "When do you open?"],
        ["Мы открываемся в восемь утра.", "Мы открыва́емся в во́семь утра́.", "My otkryvaemsya v vosem' utra.", "We open at eight in the morning."],
        ["Можно бронировать онлайн.", "Мо́жно брони́ровать онла́йн.", "Mozhno bronirovat' onlayn.", "You can book online."],
        ["Я редко ем в ресторанах.", "Я ре́дко ем в рестора́нах.", "Ya redko yem v restoranakh.", "I rarely eat in restaurants."],
        ["Дома еда вкуснее.", "До́ма еда́ вкусне́е.", "Doma yeda vkusnee.", "Food is tastier at home."],
        ["Мне нужно купить продукты.", "Мне ну́жно купи́ть проду́кты.", "Mne nuzhno kupit' produkty.", "I need to buy groceries."],
        ["Что нужно купить?", "Что ну́жно купи́ть?", "Chto nuzhno kupit'?", "What do we need to buy?"],
        ["Нам нужны яйца и масло.", "Нам нужны́ я́йца и ма́сло.", "Nam nuzhny yaytsa i maslo.", "We need eggs and butter."],
        ["Я могу пойти в магазин.", "Я могу́ пойти́ в магази́н.", "Ya mogu poyti v magazin.", "I can go to the store."],
        ["Ты можешь принести хлеба?", "Ты мо́жешь принести́ хле́ба?", "Ty mozhesh' prinesti khleba?", "Can you bring some bread?"],
        ["Нельзя есть так много сладкого.", "Нельзя́ есть так мно́го сла́дкого.", "Nel'zya yest' tak mnogo sladkogo.", "You shouldn't eat so much sweets."],
        ["Тебе нужно пить больше воды.", "Тебе́ ну́жно пить бо́льше воды́.", "Tebe nuzhno pit' bol'she vody.", "You need to drink more water."],
        ["Я должен похудеть.", "Я до́лжен похуде́ть.", "Ya dolzhen pokhudet'.", "I must lose weight."],
        ["Я начал диету.", "Я на́чал дие́ту.", "Ya nachal dietu.", "I started a diet."],
        ["Без хлеба я не могу.", "Без хле́ба я не могу́.", "Bez khleba ya ne mogu.", "I can't go without bread."],
        ["Сегодня я готовлю ужин.", "Сего́дня я гото́влю у́жин.", "Segodnya ya gotovlyu uzhin.", "Today I'm cooking dinner."],
        ["Что будем готовить?", "Что бу́дем гото́вить?", "Chto budem gotovit'?", "What shall we cook?"],
        ["Давай сделаем салат.", "Дава́й сде́лаем сала́т.", "Davay sdelaem salat.", "Let's make a salad."],
        ["Помоги мне порезать овощи.", "Помоги́ мне поре́зать о́вощи.", "Pomogi mne porezat' ovoshchi.", "Help me chop the vegetables."],
        ["Поставь воду на плиту.", "Поста́вь во́ду на плиту́.", "Postav' vodu na plitu.", "Put the water on the stove."],
        ["Добавь немного соли.", "Доба́вь немно́го со́ли.", "Dobav' nemnogo soli.", "Add a little salt."],
        ["Не пересоли!", "Не пересоли́!", "Ne peresoli!", "Don't oversalt!"],
        ["Это слишком пресно.", "Э́то сли́шком пре́сно.", "Eto slishkom presno.", "This is too bland."],
        ["Нужно больше специй.", "Ну́жно бо́льше спе́ций.", "Nuzhno bol'she spetsiy.", "We need more spices."],
        ["Ужин готов!", "У́жин гото́в!", "Uzhin gotov!", "Dinner is ready!"],
        ["Садись за стол.", "Сади́сь за стол.", "Sadis' za stol.", "Sit down at the table."],
        ["Я налью тебе вина?", "Я налью́ тебе́ вина́?", "Ya nal'yu tebe vina?", "Shall I pour you wine?"],
        ["Спасибо, мне воды.", "Спаси́бо, мне воды́.", "Spasibo, mne vody.", "Thanks, water for me."],
        ["Я не пью алкоголь.", "Я не пью алкого́ль.", "Ya ne p'yu alkogol'.", "I don't drink alcohol."],
        ["Можно мне сок?", "Мо́жно мне сок?", "Mozhno mne sok?", "May I have juice?"],
        ["Какой сок есть?", "Како́й сок есть?", "Kakoy sok yest'?", "What juice is there?"],
        ["Апельсиновый и яблочный.", "Апельси́новый и я́блочный.", "Apel'sinovyy i yablochnyy.", "Orange and apple."],
        ["Я возьму апельсиновый.", "Я возьму́ апельси́новый.", "Ya voz'mu apel'sinovyy.", "I'll have orange."],
        ["Что хочешь на ужин?", "Что хо́чешь на у́жин?", "Chto khochesh' na uzhin?", "What do you want for dinner?"],
        ["Мне всё равно.", "Мне всё равно́.", "Mne vsyo ravno.", "I don't care."],
        ["Тогда закажем суши.", "Тогда́ зака́жем су́ши.", "Togda zakazhem sushi.", "Then let's order sushi."],
        ["Хорошая идея!", "Хоро́шая иде́я!", "Khoroshaya ideya!", "Good idea!"],
        ["Курица была пересушена.", "Ку́рица была́ пересу́шена.", "Kuritsa byla peresushena.", "The chicken was overcooked."],
        ["Этот суп идеальный.", "Э́тот суп идеа́льный.", "Etot sup ideal'nyy.", "This soup is perfect."],
        ["Можно мне ещё порцию?", "Мо́жно мне ещё по́рцию?", "Mozhno mne yeshchyo portsiyu?", "May I have another portion?"],
        ["Я не могу больше есть.", "Я не могу́ бо́льше есть.", "Ya ne mogu bol'she yest'.", "I can't eat any more."],
        ["Я объелся.", "Я объе́лся.", "Ya ob'yelsya.", "I'm stuffed."],
        ["Мы должны заплатить отдельно.", "Мы должны́ заплати́ть отде́льно.", "My dolzhny zaplatit' otdel'no.", "We need to pay separately."],
        ["Я плачу за всех.", "Я плачу́ за всех.", "Ya plachu za vsekh.", "I'm paying for everyone."],
        ["Спасибо, ты очень щедрый.", "Спаси́бо, ты о́чень ще́дрый.", "Spasibo, ty ochen' shchedryy.", "Thanks, you're very generous."],
        ["В следующий раз я угощаю.", "В сле́дующий раз я угоща́ю.", "V sleduyushchiy raz ya ugoshchayu.", "Next time it's on me."],
    ],
    "a2-part-3": [
        # Travel, transport, future plans
        ["Я хочу поехать в Италию.", "Я хочу́ пое́хать в Ита́лию.", "Ya khochu poekhat' v Italiyu.", "I want to go to Italy."],
        ["Куда ты едешь летом?", "Куда́ ты е́дешь ле́том?", "Kuda ty edesh' letom?", "Where are you going this summer?"],
        ["Я еду в Грецию.", "Я е́ду в Гре́цию.", "Ya yedu v Gretsiyu.", "I'm going to Greece."],
        ["Это будет первый раз.", "Э́то бу́дет пе́рвый раз.", "Eto budet pervyy raz.", "It'll be the first time."],
        ["Я давно мечтал об этом.", "Я давно́ мечта́л об э́том.", "Ya davno mechtal ob etom.", "I've dreamed about it for a long time."],
        ["Когда у тебя отпуск?", "Когда́ у тебя́ о́тпуск?", "Kogda u tebya otpusk?", "When is your vacation?"],
        ["Отпуск в июле.", "О́тпуск в ию́ле.", "Otpusk v iyule.", "Vacation is in July."],
        ["Я возьму две недели.", "Я возьму́ две неде́ли.", "Ya voz'mu dve nedeli.", "I'll take two weeks."],
        ["Куда лучше поехать?", "Куда́ лу́чше пое́хать?", "Kuda luchshe poekhat'?", "Where's the best place to go?"],
        ["Можно поехать на море.", "Мо́жно пое́хать на мо́ре.", "Mozhno poekhat' na more.", "We can go to the sea."],
        ["Я люблю горы.", "Я люблю́ го́ры.", "Ya lyublyu gory.", "I love the mountains."],
        ["В горах прохладно даже летом.", "В гора́х прохла́дно да́же ле́том.", "V gorakh prokhladno dazhe letom.", "It's cool in the mountains even in summer."],
        ["Я полечу самолётом.", "Я полечу́ самолётом.", "Ya polechu samolyotom.", "I'll fly by plane."],
        ["Я боюсь летать.", "Я бою́сь лета́ть.", "Ya boyus' letat'.", "I'm afraid to fly."],
        ["Поезд безопаснее самолёта?", "По́езд безопа́снее самолёта?", "Poezd bezopasnee samolyota?", "Is the train safer than the plane?"],
        ["Поездом дольше, но интереснее.", "По́ездом до́льше, но интере́снее.", "Poezdom dol'she, no interesnee.", "By train is longer but more interesting."],
        ["Сколько стоит билет?", "Ско́лько сто́ит биле́т?", "Skol'ko stoit bilet?", "How much does a ticket cost?"],
        ["Билет в одну сторону.", "Биле́т в одну́ сто́рону.", "Bilet v odnu storonu.", "A one-way ticket."],
        ["Билет туда и обратно.", "Биле́т туда́ и обра́тно.", "Bilet tuda i obratno.", "A round-trip ticket."],
        ["Когда отправляется поезд?", "Когда́ отправля́ется по́езд?", "Kogda otpravlyaetsya poezd?", "When does the train leave?"],
        ["Поезд отходит в восемь утра.", "По́езд отхо́дит в во́семь утра́.", "Poezd otkhodit v vosem' utra.", "The train leaves at eight a.m."],
        ["С какого вокзала?", "С како́го вокза́ла?", "S kakogo vokzala?", "From which station?"],
        ["С Ленинградского вокзала.", "С Ленингра́дского вокза́ла.", "S Leningradskogo vokzala.", "From Leningradsky station."],
        ["Где платформа номер пять?", "Где платфо́рма но́мер пять?", "Gde platforma nomer pyat'?", "Where is platform five?"],
        ["Мой вагон номер двенадцать.", "Мой ваго́н но́мер двена́дцать.", "Moy vagon nomer dvenadtsat'.", "My carriage is number twelve."],
        ["Это моё место.", "Э́то моё ме́сто.", "Eto moyo mesto.", "This is my seat."],
        ["Извините, вы заняли моё место.", "Извини́те, вы заня́ли моё ме́сто.", "Izvinite, vy zanyali moyo mesto.", "Excuse me, you took my seat."],
        ["Простите, я ошибся.", "Прости́те, я оши́бся.", "Prostite, ya oshibsya.", "Sorry, I made a mistake."],
        ["Сколько времени в пути?", "Ско́лько вре́мени в пути́?", "Skol'ko vremeni v puti?", "How long is the journey?"],
        ["Шесть часов.", "Шесть часо́в.", "Shest' chasov.", "Six hours."],
        ["Когда мы приедем?", "Когда́ мы прие́дем?", "Kogda my priedem?", "When will we arrive?"],
        ["Мы прибудем в восемь вечера.", "Мы прибу́дем в во́семь ве́чера.", "My pribudem v vosem' vechera.", "We'll arrive at eight in the evening."],
        ["Поезд опаздывает.", "По́езд опа́здывает.", "Poezd opazdyvaet.", "The train is late."],
        ["Рейс задерживается.", "Рейс заде́рживается.", "Reys zaderzhivaetsya.", "The flight is delayed."],
        ["Где мой багаж?", "Где мой бага́ж?", "Gde moy bagazh?", "Where is my luggage?"],
        ["Я потерял чемодан.", "Я потеря́л чемода́н.", "Ya poteryal chemodan.", "I lost my suitcase."],
        ["Какой у вас номер рейса?", "Како́й у вас но́мер ре́йса?", "Kakoy u vas nomer reysa?", "What's your flight number?"],
        ["Рейс номер двести десять.", "Рейс но́мер две́сти де́сять.", "Reys nomer dvesti desyat'.", "Flight number two hundred ten."],
        ["Где регистрация?", "Где регистра́ция?", "Gde registratsiya?", "Where is check-in?"],
        ["Я зарегистрировался онлайн.", "Я зарегистри́ровался онла́йн.", "Ya zaregistrirovalsya onlayn.", "I checked in online."],
        ["Покажите ваш паспорт.", "Покажи́те ваш па́спорт.", "Pokazhite vash pasport.", "Show your passport."],
        ["Вот мой посадочный талон.", "Вот мой поса́дочный тало́н.", "Vot moy posadochnyy talon.", "Here's my boarding pass."],
        ["Где выход на посадку?", "Где вы́ход на поса́дку?", "Gde vykhod na posadku?", "Where is the boarding gate?"],
        ["Выход номер семь.", "Вы́ход но́мер семь.", "Vykhod nomer sem'.", "Gate number seven."],
        ["У окна или у прохода?", "У окна́ и́ли у прохо́да?", "U okna ili u prokhoda?", "Window or aisle?"],
        ["Мне у окна, пожалуйста.", "Мне у окна́, пожа́луйста.", "Mne u okna, pozhaluysta.", "Window for me, please."],
        ["Самолёт взлетает.", "Самолёт взлета́ет.", "Samolyot vzletaet.", "The plane is taking off."],
        ["Пристегните ремни.", "Пристегни́те ремни́.", "Pristegnite remni.", "Fasten your seatbelts."],
        ["Полёт прошёл хорошо.", "Полёт прошёл хорошо́.", "Polyot proshyol khorosho.", "The flight went well."],
        ["Мы приземлились вовремя.", "Мы приземли́лись во́время.", "My prizemlilis' vovremya.", "We landed on time."],
        ["Как добраться до центра?", "Как добра́ться до це́нтра?", "Kak dobrat'sya do tsentra?", "How do I get to the center?"],
        ["На автобусе или такси.", "На авто́бусе и́ли такси́.", "Na avtobuse ili taksi.", "By bus or taxi."],
        ["Вызовите мне такси.", "Вы́зовите мне такси́.", "Vyzovite mne taksi.", "Call me a taxi."],
        ["Сколько до аэропорта?", "Ско́лько до аэропо́рта?", "Skol'ko do aeroporta?", "How much to the airport?"],
        ["Тысяча рублей.", "Ты́сяча рубле́й.", "Tysyacha rubley.", "A thousand rubles."],
        ["Поехали!", "Пое́хали!", "Poekhali!", "Let's go!"],
        ["Остановите здесь, пожалуйста.", "Останови́те здесь, пожа́луйста.", "Ostanovite zdes', pozhaluysta.", "Stop here, please."],
        ["Я тороплюсь.", "Я тороплю́сь.", "Ya toroplyus'.", "I'm in a hurry."],
        ["Поезжайте быстрее.", "Поезжа́йте быстре́е.", "Poezzhayte bystree.", "Drive faster."],
        ["Будьте осторожны на дороге.", "Бу́дьте осторо́жны на доро́ге.", "Bud'te ostorozhny na doroge.", "Be careful on the road."],
        ["Сколько ехать до отеля?", "Ско́лько е́хать до оте́ля?", "Skol'ko ekhat' do otelya?", "How long to the hotel?"],
        ["Минут двадцать.", "Мину́т два́дцать.", "Minut dvadtsat'.", "About twenty minutes."],
        ["Я забронировал номер.", "Я заброни́ровал но́мер.", "Ya zabroniroval nomer.", "I booked a room."],
        ["На какое имя бронь?", "На како́е и́мя бронь?", "Na kakoe imya bron'?", "Under what name is the booking?"],
        ["На двое ночей.", "На дво́е ноче́й.", "Na dvoe nochey.", "For two nights."],
        ["Завтрак включён?", "За́втрак включён?", "Zavtrak vklyuchyon?", "Is breakfast included?"],
        ["Да, с семи до десяти.", "Да, с семи́ до десяти́.", "Da, s semi do desyati.", "Yes, from seven to ten."],
        ["В номере есть вай-фай?", "В но́мере есть вай-фа́й?", "V nomere yest' vay-fay?", "Is there Wi-Fi in the room?"],
        ["Какой пароль?", "Како́й паро́ль?", "Kakoy parol'?", "What's the password?"],
        ["Пароль на карточке.", "Паро́ль на ка́рточке.", "Parol' na kartochke.", "The password is on the card."],
        ["Где лифт?", "Где лифт?", "Gde lift?", "Where's the elevator?"],
        ["На каком этаже?", "На како́м этаже́?", "Na kakom etazhe?", "On what floor?"],
        ["На пятом этаже.", "На пя́том этаже́.", "Na pyatom etazhe.", "On the fifth floor."],
        ["Можно поздний выезд?", "Мо́жно по́здний вы́езд?", "Mozhno pozdniy vyezd?", "Can I check out late?"],
        ["Я уезжаю завтра.", "Я уезжа́ю за́втра.", "Ya uezzhayu zavtra.", "I'm leaving tomorrow."],
        ["Спасибо за гостеприимство.", "Спаси́бо за гостеприи́мство.", "Spasibo za gostepriimstvo.", "Thanks for the hospitality."],
        ["Я обязательно вернусь.", "Я обяза́тельно верну́сь.", "Ya obyazatel'no vernus'.", "I'll definitely come back."],
        ["Какие достопримечательности посмотреть?", "Каки́е достопримеча́тельности посмотре́ть?", "Kakie dostoprimechatel'nosti posmotret'?", "What sights should I see?"],
        ["Не пропустите старый город.", "Не пропусти́те ста́рый го́род.", "Ne propustite staryy gorod.", "Don't miss the old town."],
        ["Куда сходить вечером?", "Куда́ сходи́ть ве́чером?", "Kuda skhodit' vecherom?", "Where to go in the evening?"],
        ["В центре много баров.", "В це́нтре мно́го ба́ров.", "V tsentre mnogo barov.", "There are many bars downtown."],
        ["Я был в музее.", "Я был в музе́е.", "Ya byl v muzee.", "I was at the museum."],
        ["Музей открыт до шести.", "Музе́й откры́т до шести́.", "Muzey otkryt do shesti.", "The museum is open until six."],
        ["Сколько стоит вход?", "Ско́лько сто́ит вход?", "Skol'ko stoit vkhod?", "How much is admission?"],
        ["Триста рублей.", "Три́ста рубле́й.", "Trista rubley.", "Three hundred rubles."],
        ["У студентов скидка.", "У студе́нтов ски́дка.", "U studentov skidka.", "Students get a discount."],
        ["Где я могу купить карту?", "Где я могу́ купи́ть ка́рту?", "Gde ya mogu kupit' kartu?", "Where can I buy a map?"],
        ["Карты есть в киоске.", "Ка́рты есть в кио́ске.", "Karty yest' v kioske.", "Maps are at the kiosk."],
        ["Где ближайшая станция метро?", "Где ближа́йшая ста́нция метро́?", "Gde blizhayshaya stantsiya metro?", "Where's the nearest metro station?"],
        ["Прямо и направо.", "Пря́мо и напра́во.", "Pryamo i napravo.", "Straight and to the right."],
        ["Сколько остановок до центра?", "Ско́лько остано́вок до це́нтра?", "Skol'ko ostanovok do tsentra?", "How many stops to the center?"],
        ["Три остановки.", "Три остано́вки.", "Tri ostanovki.", "Three stops."],
        ["На какой станции выходить?", "На како́й ста́нции выходи́ть?", "Na kakoy stantsii vykhodit'?", "At which station do I get off?"],
        ["Выходите на Пушкинской.", "Выходи́те на Пу́шкинской.", "Vykhodite na Pushkinskoy.", "Get off at Pushkinskaya."],
        ["Сделайте пересадку.", "Сде́лайте переса́дку.", "Sdelayte peresadku.", "Make a transfer."],
        ["Я заблудился.", "Я заблуди́лся.", "Ya zabludilsya.", "I got lost."],
        ["Помогите мне, пожалуйста.", "Помоги́те мне, пожа́луйста.", "Pomogite mne, pozhaluysta.", "Help me, please."],
        ["Как пройти в центр?", "Как пройти́ в центр?", "Kak proyti v tsentr?", "How do I get to the center?"],
        ["Идите прямо два квартала.", "Иди́те пря́мо два кварта́ла.", "Idite pryamo dva kvartala.", "Walk straight for two blocks."],
        ["Это далеко?", "Э́то далеко́?", "Eto daleko?", "Is it far?"],
        ["Близко, минут пять пешком.", "Бли́зко, мину́т пять пешко́м.", "Blizko, minut pyat' peshkom.", "Close, about five minutes walking."],
        ["В следующем году я поеду в Японию.", "В сле́дующем году́ я пое́ду в Япо́нию.", "V sleduyushchem godu ya poedu v Yaponiyu.", "Next year I'll go to Japan."],
        ["Это моя мечта.", "Э́то моя́ мечта́.", "Eto moya mechta.", "It's my dream."],
        ["Я начну копить деньги.", "Я начну́ копи́ть де́ньги.", "Ya nachnu kopit' den'gi.", "I'll start saving money."],
        ["Я буду экономить.", "Я бу́ду эконо́мить.", "Ya budu ekonomit'.", "I'll save up."],
        ["Куда вы поедете на праздники?", "Куда́ вы пое́дете на пра́здники?", "Kuda vy poedete na prazdniki?", "Where will you go for the holidays?"],
        ["Мы поедем к родителям.", "Мы пое́дем к роди́телям.", "My poedem k roditelyam.", "We'll visit our parents."],
        ["Они живут в деревне.", "Они́ живу́т в дере́вне.", "Oni zhivut v derevne.", "They live in the countryside."],
        ["Я давно их не видел.", "Я давно́ их не ви́дел.", "Ya davno ikh ne videl.", "I haven't seen them in a long time."],
        ["Я возьму с собой подарки.", "Я возьму́ с собо́й пода́рки.", "Ya voz'mu s soboy podarki.", "I'll take gifts with me."],
        ["Машина в порядке?", "Маши́на в поря́дке?", "Mashina v poryadke?", "Is the car okay?"],
        ["Я проверю шины.", "Я прове́рю ши́ны.", "Ya proveryu shiny.", "I'll check the tires."],
        ["Нужно заправиться.", "Ну́жно запра́виться.", "Nuzhno zapravit'sya.", "We need to refuel."],
        ["Заправка через километр.", "Запра́вка че́рез киломе́тр.", "Zapravka cherez kilometr.", "Gas station in a kilometer."],
        ["Полный бак, пожалуйста.", "По́лный бак, пожа́луйста.", "Polnyy bak, pozhaluysta.", "Full tank, please."],
        ["Я в пробке.", "Я в про́бке.", "Ya v probke.", "I'm in a traffic jam."],
        ["Дорога свободная.", "Доро́га свобо́дная.", "Doroga svobodnaya.", "The road is clear."],
        ["Какая скорость разрешена?", "Кака́я ско́рость разрешена́?", "Kakaya skorost' razreshena?", "What's the speed limit?"],
        ["Сто километров в час.", "Сто киломе́тров в час.", "Sto kilometrov v chas.", "A hundred kilometers an hour."],
        ["Не превышай скорость.", "Не превыша́й ско́рость.", "Ne prevyshay skorost'.", "Don't speed."],
        ["Меня остановила полиция.", "Меня́ останови́ла поли́ция.", "Menya ostanovila politsiya.", "The police stopped me."],
        ["Документы, пожалуйста.", "Докуме́нты, пожа́луйста.", "Dokumenty, pozhaluysta.", "Documents, please."],
        ["Вот мои права.", "Вот мои́ права́.", "Vot moi prava.", "Here's my license."],
        ["Где парковка?", "Где парко́вка?", "Gde parkovka?", "Where's the parking?"],
        ["Здесь нельзя парковаться.", "Здесь нельзя́ паркова́ться.", "Zdes' nel'zya parkovat'sya.", "You can't park here."],
        ["Сколько стоит час парковки?", "Ско́лько сто́ит час парко́вки?", "Skol'ko stoit chas parkovki?", "How much per hour for parking?"],
        ["Бесплатная парковка.", "Беспла́тная парко́вка.", "Besplatnaya parkovka.", "Free parking."],
        ["Путешествие было прекрасное.", "Путеше́ствие бы́ло прекра́сное.", "Puteshestvie bylo prekrasnoe.", "The trip was wonderful."],
    ],
    "a2-part-4": [
        # Weather, clothing, feelings
        ["Какая сегодня погода?", "Кака́я сего́дня пого́да?", "Kakaya segodnya pogoda?", "What's the weather like today?"],
        ["Сегодня тепло и солнечно.", "Сего́дня тепло́ и со́лнечно.", "Segodnya teplo i solnechno.", "Today is warm and sunny."],
        ["На улице холодно.", "На у́лице хо́лодно.", "Na ulitse kholodno.", "It's cold outside."],
        ["Идёт дождь.", "Идёт дождь.", "Idyot dozhd'.", "It's raining."],
        ["Возьми зонт.", "Возьми́ зонт.", "Voz'mi zont.", "Take an umbrella."],
        ["Я промок до нитки.", "Я промо́к до ни́тки.", "Ya promok do nitki.", "I got soaked to the skin."],
        ["Утром был мороз.", "У́тром был моро́з.", "Utrom byl moroz.", "It was frosty in the morning."],
        ["Минус десять градусов.", "Ми́нус де́сять гра́дусов.", "Minus desyat' gradusov.", "Minus ten degrees."],
        ["Какая температура на улице?", "Кака́я температу́ра на у́лице?", "Kakaya temperatura na ulitse?", "What's the temperature outside?"],
        ["Плюс двадцать.", "Плюс два́дцать.", "Plyus dvadtsat'.", "Plus twenty."],
        ["Идёт снег.", "Идёт снег.", "Idyot sneg.", "It's snowing."],
        ["Зима в этом году тёплая.", "Зима́ в э́том году́ тёплая.", "Zima v etom godu tyoplaya.", "Winter is warm this year."],
        ["Я не люблю холод.", "Я не люблю́ хо́лод.", "Ya ne lyublyu kholod.", "I don't like the cold."],
        ["Лето моё любимое время года.", "Ле́то моё люби́мое вре́мя го́да.", "Leto moyo lyubimoe vremya goda.", "Summer is my favorite season."],
        ["Сегодня очень жарко.", "Сего́дня о́чень жа́рко.", "Segodnya ochen' zharko.", "It's very hot today."],
        ["Тридцать градусов в тени.", "Три́дцать гра́дусов в тени́.", "Tridtsat' gradusov v teni.", "Thirty degrees in the shade."],
        ["Я устал от жары.", "Я уста́л от жары́.", "Ya ustal ot zhary.", "I'm tired of the heat."],
        ["Завтра обещают дождь.", "За́втра обеща́ют дождь.", "Zavtra obeshchayut dozhd'.", "They forecast rain tomorrow."],
        ["Прогноз погоды плохой.", "Прогно́з пого́ды плохо́й.", "Prognoz pogody plokhoy.", "The weather forecast is bad."],
        ["Дует сильный ветер.", "Ду́ет си́льный ве́тер.", "Duet sil'nyy veter.", "A strong wind is blowing."],
        ["Небо облачное.", "Не́бо о́блачное.", "Nebo oblachnoe.", "The sky is cloudy."],
        ["Ни облачка на небе.", "Ни о́блачка на не́бе.", "Ni oblachka na nebe.", "Not a cloud in the sky."],
        ["Солнце светит ярко.", "Со́лнце све́тит я́рко.", "Solntse svetit yarko.", "The sun is shining brightly."],
        ["Скоро будет гроза.", "Ско́ро бу́дет гроза́.", "Skoro budet groza.", "There'll be a thunderstorm soon."],
        ["Я боюсь молний.", "Я бою́сь мо́лний.", "Ya boyus' molniy.", "I'm afraid of lightning."],
        ["Слышен гром.", "Слы́шен гром.", "Slyshen grom.", "Thunder can be heard."],
        ["Весной всё зацветает.", "Весно́й всё зацвета́ет.", "Vesnoy vsyo zatsvetaet.", "In spring everything blooms."],
        ["Осенью листья жёлтые.", "О́сенью ли́стья жёлтые.", "Osen'yu list'ya zhyoltye.", "In autumn leaves are yellow."],
        ["Сегодня хорошая погода для прогулки.", "Сего́дня хоро́шая пого́да для прогу́лки.", "Segodnya khoroshaya pogoda dlya progulki.", "Today is good weather for a walk."],
        ["Я надену пальто.", "Я наде́ну пальто́.", "Ya nadenu pal'to.", "I'll put on a coat."],
        ["Где моя шапка?", "Где моя́ ша́пка?", "Gde moya shapka?", "Where's my hat?"],
        ["Не забудь шарф.", "Не забу́дь шарф.", "Ne zabud' sharf.", "Don't forget your scarf."],
        ["Я ношу очки.", "Я ношу́ очки́.", "Ya noshu ochki.", "I wear glasses."],
        ["Эти ботинки удобные.", "Э́ти боти́нки удо́бные.", "Eti botinki udobnye.", "These boots are comfortable."],
        ["Мне нужны новые туфли.", "Мне нужны́ но́вые ту́фли.", "Mne nuzhny novye tufli.", "I need new shoes."],
        ["Какой у вас размер?", "Како́й у вас разме́р?", "Kakoy u vas razmer?", "What's your size?"],
        ["У меня сорок второй.", "У меня́ со́рок второ́й.", "U menya sorok vtoroy.", "I'm a forty-two."],
        ["Можно примерить?", "Мо́жно приме́рить?", "Mozhno primerit'?", "May I try it on?"],
        ["Где примерочная?", "Где приме́рочная?", "Gde primerochnaya?", "Where's the fitting room?"],
        ["Эта рубашка мне велика.", "Э́та руба́шка мне велика́.", "Eta rubashka mne velika.", "This shirt is too big for me."],
        ["Эти джинсы малы.", "Э́ти джи́нсы малы́.", "Eti dzhinsy maly.", "These jeans are too small."],
        ["Есть размер поменьше?", "Есть разме́р поме́ньше?", "Yest' razmer pomen'she?", "Is there a smaller size?"],
        ["Это мне подходит.", "Э́то мне подхо́дит.", "Eto mne podkhodit.", "This fits me."],
        ["Тебе очень идёт.", "Тебе́ о́чень идёт.", "Tebe ochen' idyot.", "It suits you very well."],
        ["Какой цвет вы хотите?", "Како́й цвет вы хоти́те?", "Kakoy tsvet vy khotite?", "What color do you want?"],
        ["Я люблю чёрный.", "Я люблю́ чёрный.", "Ya lyublyu chyornyy.", "I like black."],
        ["А белого нет?", "А бе́лого нет?", "A belogo net?", "Is there no white?"],
        ["Сколько стоит это платье?", "Ско́лько сто́ит э́то пла́тье?", "Skol'ko stoit eto plat'e?", "How much is this dress?"],
        ["Это дорого для меня.", "Э́то до́рого для меня́.", "Eto dorogo dlya menya.", "That's expensive for me."],
        ["Есть скидка?", "Есть ски́дка?", "Yest' skidka?", "Is there a discount?"],
        ["Сейчас распродажа.", "Сейча́с распрода́жа.", "Seychas rasprodazha.", "There's a sale right now."],
        ["Я возьму это.", "Я возьму́ э́то.", "Ya voz'mu eto.", "I'll take this."],
        ["Где касса?", "Где ка́сса?", "Gde kassa?", "Where's the cashier?"],
        ["Я сегодня в хорошем настроении.", "Я сего́дня в хоро́шем настрое́нии.", "Ya segodnya v khoroshem nastroenii.", "I'm in a good mood today."],
        ["Мне грустно.", "Мне гру́стно.", "Mne grustno.", "I'm sad."],
        ["Я очень рад.", "Я о́чень рад.", "Ya ochen' rad.", "I'm very glad."],
        ["Я счастлив.", "Я сча́стлив.", "Ya schastliv.", "I'm happy."],
        ["Что с тобой?", "Что с тобо́й?", "Chto s toboy?", "What's wrong with you?"],
        ["Я просто устал.", "Я про́сто уста́л.", "Ya prosto ustal.", "I'm just tired."],
        ["Не волнуйся.", "Не волну́йся.", "Ne volnuysya.", "Don't worry."],
        ["Я волнуюсь за тебя.", "Я волну́юсь за тебя́.", "Ya volnuyus' za tebya.", "I'm worried about you."],
        ["Всё будет хорошо.", "Всё бу́дет хорошо́.", "Vsyo budet khorosho.", "Everything will be okay."],
        ["Я тебя понимаю.", "Я тебя́ понима́ю.", "Ya tebya ponimayu.", "I understand you."],
        ["Я скучаю по тебе.", "Я скуча́ю по тебе́.", "Ya skuchayu po tebe.", "I miss you."],
        ["Я люблю тебя.", "Я люблю́ тебя́.", "Ya lyublyu tebya.", "I love you."],
        ["Я тебя обожаю.", "Я тебя́ обожа́ю.", "Ya tebya obozhayu.", "I adore you."],
        ["Спасибо за всё.", "Спаси́бо за всё.", "Spasibo za vsyo.", "Thanks for everything."],
        ["Я благодарен тебе.", "Я благода́рен тебе́.", "Ya blagodaren tebe.", "I'm grateful to you."],
        ["Прости меня.", "Прости́ меня́.", "Prosti menya.", "Forgive me."],
        ["Я виноват.", "Я винова́т.", "Ya vinovat.", "It's my fault."],
        ["Не сердись.", "Не серди́сь.", "Ne serdis'.", "Don't be angry."],
        ["Я не сержусь.", "Я не сержу́сь.", "Ya ne serzhus'.", "I'm not angry."],
        ["Я разочарован.", "Я разочаро́ван.", "Ya razocharovan.", "I'm disappointed."],
        ["Это меня раздражает.", "Э́то меня́ раздража́ет.", "Eto menya razdrazhaet.", "This annoys me."],
        ["Я в шоке.", "Я в шо́ке.", "Ya v shoke.", "I'm shocked."],
        ["Не может быть!", "Не мо́жет быть!", "Ne mozhet byt'!", "Can't be!"],
        ["Я удивлён.", "Я удивлён.", "Ya udivlyon.", "I'm surprised."],
        ["Какой сюрприз!", "Како́й сюрпри́з!", "Kakoy syurpriz!", "What a surprise!"],
        ["Я горжусь тобой.", "Я горжу́сь тобо́й.", "Ya gorzhus' toboy.", "I'm proud of you."],
        ["Молодец!", "Молоде́ц!", "Molodets!", "Well done!"],
        ["Я завидую тебе.", "Я зави́дую тебе́.", "Ya zaviduyu tebe.", "I envy you."],
        ["Мне страшно.", "Мне стра́шно.", "Mne strashno.", "I'm scared."],
        ["Не бойся.", "Не бо́йся.", "Ne boysya.", "Don't be afraid."],
        ["Я нервничаю.", "Я не́рвничаю.", "Ya nervnichayu.", "I'm nervous."],
        ["Успокойся, пожалуйста.", "Успоко́йся, пожа́луйста.", "Uspokoysya, pozhaluysta.", "Calm down, please."],
        ["Я в порядке.", "Я в поря́дке.", "Ya v poryadke.", "I'm okay."],
        ["Мне неудобно.", "Мне неудо́бно.", "Mne neudobno.", "I feel uncomfortable."],
        ["Это смешно!", "Э́то смешно́!", "Eto smeshno!", "That's funny!"],
        ["Мне скучно.", "Мне ску́чно.", "Mne skuchno.", "I'm bored."],
        ["Это интересно.", "Э́то интере́сно.", "Eto interesno.", "That's interesting."],
        ["Я в восторге.", "Я в восто́рге.", "Ya v vostorge.", "I'm thrilled."],
        ["Я разочарован результатом.", "Я разочаро́ван результа́том.", "Ya razocharovan rezul'tatom.", "I'm disappointed with the result."],
        ["Мне всё равно.", "Мне всё равно́.", "Mne vsyo ravno.", "I don't care."],
        ["Я не знаю, что делать.", "Я не зна́ю, что де́лать.", "Ya ne znayu, chto delat'.", "I don't know what to do."],
        ["Я сомневаюсь.", "Я сомнева́юсь.", "Ya somnevayus'.", "I have doubts."],
        ["Я уверен в этом.", "Я уве́рен в э́том.", "Ya uveren v etom.", "I'm sure of that."],
        ["Я не уверен.", "Я не уве́рен.", "Ya ne uveren.", "I'm not sure."],
        ["Подумай хорошо.", "Поду́май хорошо́.", "Podumay khorosho.", "Think it over well."],
        ["Я подумаю.", "Я поду́маю.", "Ya podumayu.", "I'll think about it."],
        ["Это сложный выбор.", "Э́то сло́жный вы́бор.", "Eto slozhnyy vybor.", "It's a tough choice."],
        ["Я надеюсь на лучшее.", "Я наде́юсь на лу́чшее.", "Ya nadeyus' na luchshee.", "I hope for the best."],
        ["Не теряй надежду.", "Не теря́й наде́жду.", "Ne teryay nadezhdu.", "Don't lose hope."],
        ["Я верю в тебя.", "Я ве́рю в тебя́.", "Ya veryu v tebya.", "I believe in you."],
        ["Ты можешь это сделать.", "Ты мо́жешь э́то сде́лать.", "Ty mozhesh' eto sdelat'.", "You can do this."],
        ["Я готов.", "Я гото́в.", "Ya gotov.", "I'm ready."],
        ["Я не готова.", "Я не гото́ва.", "Ya ne gotova.", "I'm not ready."],
        ["Я опаздываю.", "Я опа́здываю.", "Ya opazdyvayu.", "I'm running late."],
        ["Поторопись!", "Поторопи́сь!", "Potoropis'!", "Hurry up!"],
        ["Я уже здесь.", "Я уже́ здесь.", "Ya uzhe zdes'.", "I'm already here."],
        ["Подожди минутку.", "Подожди́ мину́тку.", "Podozhdi minutku.", "Wait a minute."],
        ["Я скоро приду.", "Я ско́ро приду́.", "Ya skoro pridu.", "I'll be there soon."],
        ["Куртка тёплая?", "Ку́ртка тёплая?", "Kurtka tyoplaya?", "Is the jacket warm?"],
        ["Эта куртка слишком тонкая.", "Э́та ку́ртка сли́шком то́нкая.", "Eta kurtka slishkom tonkaya.", "This jacket is too thin."],
        ["Надень что-нибудь потеплее.", "Наде́нь что-нибу́дь потепле́е.", "Naden' chto-nibud' poteplee.", "Wear something warmer."],
        ["На мне свитер.", "На мне сви́тер.", "Na mne sviter.", "I'm wearing a sweater."],
        ["Я в футболке и шортах.", "Я в футбо́лке и шо́ртах.", "Ya v futbolke i shortakh.", "I'm in a T-shirt and shorts."],
        ["Дома хожу в тапочках.", "До́ма хожу́ в та́почках.", "Doma khozhu v tapochkakh.", "At home I wear slippers."],
        ["Не забудь перчатки.", "Не забу́дь перча́тки.", "Ne zabud' perchatki.", "Don't forget your gloves."],
        ["На улице гололёд.", "На у́лице гололёд.", "Na ulitse gololyod.", "There's ice outside."],
        ["Будь осторожен, скользко.", "Будь осторо́жен, ско́льзко.", "Bud' ostorozhen, skol'zko.", "Be careful, it's slippery."],
        ["Я упал на льду.", "Я упа́л на льду́.", "Ya upal na l'du.", "I fell on the ice."],
        ["Тебе больно?", "Тебе́ бо́льно?", "Tebe bol'no?", "Are you hurt?"],
        ["Немного, но всё нормально.", "Немно́го, но всё норма́льно.", "Nemnogo, no vsyo normal'no.", "A little, but everything's fine."],
        ["Радуга после дождя!", "Ра́дуга по́сле дождя́!", "Raduga posle dozhdya!", "A rainbow after the rain!"],
        ["Это так красиво.", "Э́то так краси́во.", "Eto tak krasivo.", "It's so beautiful."],
        ["Я просто счастлив быть здесь.", "Я про́сто сча́стлив быть здесь.", "Ya prosto schastliv byt' zdes'.", "I'm just happy to be here."],
    ],
}

def main():
    out_dir = "src/data/sentences"
    os.makedirs(out_dir, exist_ok=True)
    for list_id, rows in PARTS.items():
        items = []
        for i, (ru, ruStressed, translit, en) in enumerate(rows, 1):
            items.append({
                "id": f"{list_id}-{i}",
                "ru": ru,
                "ruStressed": ruStressed,
                "translit": translit,
                "en": en,
            })
        path = os.path.join(out_dir, f"{list_id}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(items, f, ensure_ascii=False, indent=2)
        print(f"{list_id}: {len(items)} sentences -> {path}")

if __name__ == "__main__":
    main()
