/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ConjugationRouteImport } from './routes/conjugation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomIndexRouteImport } from './routes/custom.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TypingListIdRouteImport } from './routes/typing.$listId'
import { Route as ListListIdRouteImport } from './routes/list.$listId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as CustomSetIdRouteImport } from './routes/custom.$setId'
import { Route as AdminSentencesRouteImport } from './routes/admin.sentences'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ConjugationRoute = ConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomIndexRoute = CustomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TypingListIdRoute = TypingListIdRouteImport.update({
  id: '/typing/$listId',
  path: '/typing/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListListIdRoute = ListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomSetIdRoute = CustomSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => CustomRoute,
} as any)
const AdminSentencesRoute = AdminSentencesRouteImport.update({
  id: '/sentences',
  path: '/sentences',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/conjugation': typeof ConjugationRoute
  '/custom': typeof CustomRouteWithChildren
  '/daily': typeof DailyRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/story': typeof StoryRoute
  '/tutor': typeof TutorRoute
  '/utilities': typeof UtilitiesRoute
  '/admin/sentences': typeof AdminSentencesRoute
  '/custom/$setId': typeof CustomSetIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/list/$listId': typeof ListListIdRoute
  '/typing/$listId': typeof TypingListIdRoute
  '/admin/': typeof AdminIndexRoute
  '/custom/': typeof CustomIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conjugation': typeof ConjugationRoute
  '/daily': typeof DailyRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/story': typeof StoryRoute
  '/tutor': typeof TutorRoute
  '/utilities': typeof UtilitiesRoute
  '/admin/sentences': typeof AdminSentencesRoute
  '/custom/$setId': typeof CustomSetIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/list/$listId': typeof ListListIdRoute
  '/typing/$listId': typeof TypingListIdRoute
  '/admin': typeof AdminIndexRoute
  '/custom': typeof CustomIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/conjugation': typeof ConjugationRoute
  '/custom': typeof CustomRouteWithChildren
  '/daily': typeof DailyRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/story': typeof StoryRoute
  '/tutor': typeof TutorRoute
  '/utilities': typeof UtilitiesRoute
  '/admin/sentences': typeof AdminSentencesRoute
  '/custom/$setId': typeof CustomSetIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/list/$listId': typeof ListListIdRoute
  '/typing/$listId': typeof TypingListIdRoute
  '/admin/': typeof AdminIndexRoute
  '/custom/': typeof CustomIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conjugation'
    | '/custom'
    | '/daily'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/review'
    | '/story'
    | '/tutor'
    | '/utilities'
    | '/admin/sentences'
    | '/custom/$setId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/list/$listId'
    | '/typing/$listId'
    | '/admin/'
    | '/custom/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conjugation'
    | '/daily'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/review'
    | '/story'
    | '/tutor'
    | '/utilities'
    | '/admin/sentences'
    | '/custom/$setId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/list/$listId'
    | '/typing/$listId'
    | '/admin'
    | '/custom'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conjugation'
    | '/custom'
    | '/daily'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/review'
    | '/story'
    | '/tutor'
    | '/utilities'
    | '/admin/sentences'
    | '/custom/$setId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/list/$listId'
    | '/typing/$listId'
    | '/admin/'
    | '/custom/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConjugationRoute: typeof ConjugationRoute
  CustomRoute: typeof CustomRouteWithChildren
  DailyRoute: typeof DailyRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  StoryRoute: typeof StoryRoute
  TutorRoute: typeof TutorRoute
  UtilitiesRoute: typeof UtilitiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ListListIdRoute: typeof ListListIdRoute
  TypingListIdRoute: typeof TypingListIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conjugation': {
      id: '/conjugation'
      path: '/conjugation'
      fullPath: '/conjugation'
      preLoaderRoute: typeof ConjugationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/': {
      id: '/custom/'
      path: '/'
      fullPath: '/custom/'
      preLoaderRoute: typeof CustomIndexRouteImport
      parentRoute: typeof CustomRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/typing/$listId': {
      id: '/typing/$listId'
      path: '/typing/$listId'
      fullPath: '/typing/$listId'
      preLoaderRoute: typeof TypingListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$listId': {
      id: '/list/$listId'
      path: '/list/$listId'
      fullPath: '/list/$listId'
      preLoaderRoute: typeof ListListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/$setId': {
      id: '/custom/$setId'
      path: '/$setId'
      fullPath: '/custom/$setId'
      preLoaderRoute: typeof CustomSetIdRouteImport
      parentRoute: typeof CustomRoute
    }
    '/admin/sentences': {
      id: '/admin/sentences'
      path: '/sentences'
      fullPath: '/admin/sentences'
      preLoaderRoute: typeof AdminSentencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSentencesRoute: typeof AdminSentencesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSentencesRoute: AdminSentencesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomRouteChildren {
  CustomSetIdRoute: typeof CustomSetIdRoute
  CustomIndexRoute: typeof CustomIndexRoute
}

const CustomRouteChildren: CustomRouteChildren = {
  CustomSetIdRoute: CustomSetIdRoute,
  CustomIndexRoute: CustomIndexRoute,
}

const CustomRouteWithChildren =
  CustomRoute._addFileChildren(CustomRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ConjugationRoute: ConjugationRoute,
  CustomRoute: CustomRouteWithChildren,
  DailyRoute: DailyRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  StoryRoute: StoryRoute,
  TutorRoute: TutorRoute,
  UtilitiesRoute: UtilitiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  ListListIdRoute: ListListIdRoute,
  TypingListIdRoute: TypingListIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
